feat(SmartContracts): migrating smart contracts
WavesHQ/bridge pull request #148
Opened 2022-12-21 02:39 UTC by Abhishekkochar

#### What this PR does / why we need it:
Initial migration of Smart contracts. 
#### Which issue(s) does this PR fixes?:
Fixes #146 

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2022-12-30 03:31 UTC, cuongquangnam submitted a review, later dismissed

2022-12-30 04:32 UTC, Abhishekkochar commented
FYI @cuongquangnam, We are using the call method to withdraw ether in this PR.

2022-12-30 06:22 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        (bool sent, bytes memory data) = msg.sender.call{value: amount}("");
no need to declare data

2022-12-30 09:13 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        (bool sent, bytes memory data) = msg.sender.call{value: amount}("");
I will clear this out on next PR

2023-01-03 07:09 UTC, weiyuan95 requested changes
Did not really bother too much with reviewing the solidity contracts since that will be subject to change down the line.

2023-01-03 08:41 UTC, cuongquangnam commented on packages/smartcontracts/package.json
> +    "@openzeppelin/contracts": "^4.8.0",
Yes, I am going to make those changes in the future

2023-01-03 08:41 UTC, cuongquangnam commented on .github/workflows/ci.yml
> +          version: 7.13.3
I think @Abhishekkochar changed so as to make the CI/CD work

2023-01-03 08:56 UTC, Abhishekkochar commented on packages/smartcontracts/src/hardhat.config.ts
> +import '@nomicfoundation/hardhat-toolbox';
Instead of using other commonly using packages. We can switch to  [hardhat-toolbox](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox)

2023-01-03 09:11 UTC, weiyuan95 commented on .github/workflows/ci.yml
> +          version: 7.13.3
Ah - what was failing? Do you remember or have a link to the failing CI?

2023-01-03 09:13 UTC, weiyuan95 commented on packages/smartcontracts/package.json
> +    "@openzeppelin/contracts": "^4.8.0",
Tracked in #162

2023-01-03 09:20 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +import '@nomicfoundation/hardhat-toolbox';
<img width="744" alt="image" src="https://user-images.githubusercontent.com/35588002/210329369-077043a7-c668-4b7c-aa9c-abf4aeda9f41.png">

We probably can remove some of the dependencies then

2023-01-04 03:33 UTC, cuongquangnam commented on .github/workflows/ci.yml
> +          version: 7.13.3
https://github.com/WavesHQ/bridge/actions/runs/3798485981/jobs/6460453806#step:5:15

2023-01-04 03:40 UTC, weiyuan95 commented on .github/workflows/ci.yml
> +          version: 7.13.3
Interesting error 🤣

2023-01-04 07:14 UTC, cuongquangnam approved these changes

2023-01-04 11:01 UTC, Abhishekkochar commented on packages/smartcontracts/test-i9n/Bridge.i9n.ts
> +    operationalAdmin = await hardhatNetwork.createTestWallet();
I have fixed it as part of PR #161

2023-01-04 11:10 UTC, weiyuan95 approved these changes

2023-01-04 11:19 UTC, pierregee approved these changes

2023-01-04 11:25 UTC, merged