feat(SmartContracts/tests): Split up tests into their areas of scope.
WavesHQ/bridge pull request #161
Opened 2023-01-02 00:41 UTC by Abhishekkochar

#### What this PR does / why we need it:
As Mentioned in title, this PR introduce the fix for #156 & #155
#### Which issue(s) does this PR fixes?:
Fixes #155 
Fixes #156

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-03 07:11 UTC, weiyuan95 commented
@Abhishekkochar if this PR depends on and branches off #148, we can change the target branch from main to the branch in that PR.

2023-01-03 07:25 UTC, Abhishekkochar commented
> @Abhishekkochar if this PR depends on and branches off #148, we can change the target branch from main to the branch in that PR.

Reason I choose the  mina branch is to no wait till the 148 approved to work on.

2023-01-03 09:07 UTC, weiyuan95 requested changes

2023-01-03 09:07 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      // Sending 15 Eth as well. Users must not send ERC20 token and ETH together. Depending on token address - only the respected token will be added.
Have we added the check for this yet? I'm guessing no looking at the contract code.

We should probably open an issue for this to keep track if we haven't implemented it yet - if the increase in gas is trivial, I don't see why we should not implement this sanity check.

2023-01-03 09:07 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      // This txn should be revert with the error "B000"
```suggestion
```

2023-01-03 09:07 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +    it('Bridge request before adding support for ETH token', async () => {
```suggestion
    it('Bridge request should revert before adding support for ETH token', async () => {
```

2023-01-03 09:07 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +    it('Successfully emitting events upon bridging', async () => {
IMO I would include this with the test above, since to me, a 'successful bridge' is when the event is emitted as well for the server to pick up. That's where the responsibility of the contract ends, and it's the extent of what we can track on the EVM side.

2023-01-03 09:14 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
> +      const { proxyBridge } = await loadFixture(deployContracts);
`Hardhat will reset the state of the network to what it was at the point after the fixture was initially executed.` 
Yes it does.

2023-01-03 09:21 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.transactionFee.spec.ts
> +      const { proxyBridge } = await loadFixture(deployContracts);
Yep, and since the tests work fine it shouldn't be a problem. Just wanted to double check 😬

2023-01-03 09:24 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +error STILL_IN_CHANGE_ALLOWANCE_PERIOD();
Well in a way Yes. Current custom errors does provide better explanation than Standard ones

2023-01-03 09:40 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +error STILL_IN_CHANGE_ALLOWANCE_PERIOD();
Updated the issue.

2023-01-03 09:45 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
`defaultAdminSigner` is being used for the tx. In wei, numbers will not be the same.
<img width="857" alt="Screenshot 2023-01-03 at 5 36 24 PM" src="https://user-images.githubusercontent.com/43106142/210331901-b1da3722-0c43-44b9-ada5-6dcb746c2dad.png">

2023-01-03 09:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +    it('Changing allowance for two ERC20 tokens', async () => {
We have this tests before. Changed the name to describe what's happening in the block. Instead of changing allowance of one token, we doing two tokens one after another.

2023-01-03 09:53 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +    describe('Daily Allowance change by different accounts ', () => {
Checking who can change the daily allowance for ETH. 
Another scenario, we might have to look out for: When changing dailyAllowance for ETH, same allowance should be set for WETH as well. With current contract, this is not doable.

2023-01-03 09:54 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
What code are you using for your expectation? 🤔 Probably a rounding issue with `BigNumber` being converted to another data type

2023-01-03 09:56 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +    it('Changing allowance for two ERC20 tokens', async () => {
Hmm, but we seem to be calling `bridgeToDeFiChain` instead of `changeDailyAllowance`? Unless i'm missing something here

2023-01-03 09:58 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +    describe('Daily Allowance change by different accounts ', () => {
> Checking who can change the daily allowance for ETH.

Ah, is this because we are calling `addSupportedTokens` with a zero address? If that's the case, can we be a bit more explicit with the test names? Since there's a difference between allowance changing for ETH and ERC20 tokens.

If it's not the case, then I don't see `changeDailyAllowance` being called 😅

2023-01-03 10:20 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      // Sending 15 Eth as well. Users must not send ERC20 token and ETH together. Depending on token address - only the respected token will be added.
Added and tested now.

2023-01-03 10:22 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      // @dev will look into later
Yes, i would keep this on for now.

2023-01-04 02:52 UTC, weiyuan95 commented
> > @Abhishekkochar if this PR depends on and branches off #148, we can change the target branch from main to the branch in that PR.
> 
> Reason I choose the mina branch is to no wait till the 148 approved to work on.

Ah ok, I saw this so I assumed there were some dependencies!

> Only merged after PR #148

2023-01-04 03:12 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
Probably need to account for ether spent for transaction gas in calculation to make the correct result

2023-01-04 03:44 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +    it('Changing allowance for two ERC20 tokens', async () => {
Yes, you are correct. I have changed this now.

2023-01-04 03:48 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
<img width="857" alt="Screenshot 2023-01-03 at 5 36 24 PM" src="https://user-images.githubusercontent.com/43106142/210480908-8738d9ef-bbeb-4a58-b474-dcb8fc4e4738.png">
<img width="1020" alt="Screenshot 2023-01-04 at 11 47 44 AM" src="https://user-images.githubusercontent.com/43106142/210480948-82f3b39f-78df-4259-adc3-94dfafbdc724.png"> 
Above ones are strings, change these to bigNumber. Still the same issue.

2023-01-04 06:36 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
hmm, I'd suggest having something like this: 
```typescript
const beforeBalance = await ethers.provider.getBalance(defaultAdminSigner.address);
// 2 ETHER withdrawal by the Admin
const tx = await proxyBridge.connect(defaultAdminSigner).withdrawEth(toWei('2'));
const receipt = await tx.wait();
expect(await ethers.provider.getBalance(defaultAdminSigner.address)).to.equal(
  beforeBalance.add(toWei('2')).sub(receipt.gasUsed.mul(receipt.effectiveGasPrice)),
);```

2023-01-04 06:40 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +        console.log(
so the thing is balance of defaultAdminSigner does not only increase thanks to the withdrawal but also decrease because of gas spent

2023-01-04 12:43 UTC, closed without merging

2023-01-05 01:50 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    /**
@cuongquangnam, I believe you been working on other PR on these fallback and receive fns. Adding these ones to accept ETH for testing purpose only.

2023-01-05 06:11 UTC, weiyuan95 requested changes
1 more quick comment. Also i think there are 2 more comments that are not addressed

2023-01-05 06:11 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/testUtils/deployment.ts
> +    accounts[0],
```suggestion
    // admin address
    accounts[0],
    // operational address
    accounts[1],
    // relayer address
    accounts[0],
```

2023-01-05 06:31 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts
> +          'AccessControl: account 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc is missing role 0x0000000000000000000000000000000000000000000000000000000000000000',
These should be outdated now.

2023-01-05 06:32 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.supportedToken.spec.ts
> +    it('Successfully emitted the event when the supported token added by Admin Addresses', async () => {
This and other similar to it should be outdated now.

2023-01-05 06:37 UTC, weiyuan95 submitted a review, later dismissed
Generally LGTM, although stressing again that we should probably give the code another look before deploying to mainnet.

2023-01-05 10:22 UTC, cuongquangnam requested changes

2023-01-05 10:22 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    /**
Can you point me to the test where you test these two functions?

2023-01-05 11:31 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    /**
As mentioned above, I believe you are doing tests in your PR. I'm solely using them for the purpose of receiving ETH. Kinda shortcut instead of bridging.

2023-01-05 11:31 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = msg.sender.call{value: _amount}('');
Yes, This might cause the issue. Good catch.

2023-01-05 11:31 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +  });
Both at the end doing the same thing. We can keep them separate for the sake of name at this stage. I will be testing the daily allowance reset in this file. Prefer to keep it separate.

2023-01-06 03:34 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = msg.sender.call{value: _amount}('');
I'm quite curious - why does the nonce not increment when `claimFund` is called from the `fallback`? Is it because calling `msg.sender.call` from the bridge contract calls the `fallback` of `Attack`, which leads to a loop of funds getting claimed?

2023-01-06 06:38 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = msg.sender.call{value: _amount}('');
yup, that's what I mean

2023-01-06 07:02 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +            (bool sent, ) = msg.sender.call{value: _amount}('');
Great catch! 🔥

2023-01-06 07:36 UTC, cuongquangnam approved these changes