feat(SmartContract): reset daily allowance time for supported token
WavesHQ/bridge pull request #175
Opened 2023-01-10 09:44 UTC by Abhishekkochar

#### What this PR does / why we need it:
As the title suggests, Admins can set the `resetDailyAllowanceTime` and  reset with new `resetDailyAllowanceTime`.
#### Which issue(s) does this PR fixes?:

Fixes #158 

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-10 10:22 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (tokenAllowancesStartTime > block.timestamp)
@cuongquangnam , please have a quick look when you have time. Thanks

2023-01-11 09:59 UTC, cuongquangnam requested changes

2023-01-11 09:59 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
Have you thought of the scenario where changeDailyAllowance happens around the same time as changeResetAllowanceTime? 
```typescript
// currently, for tokenA, smart contract resets every 8am 
// at 9am today, the admin changes the daily allowance
await proxyBridge.changeDailyAllowance(tokenA.address, 100);
// later at 10am today, the admin change resetAllowanceTime to 10am tomorrow,
// which makes the resetEpoch = 10 am tomorrow
await proxyBridge.changeResetAllowanceTime(tokenA.address, 10AM_TOMORROW)
// now whenever the modifier notInChangePeriod(tokenA.address) runs, 
// it will check block.timestamp - 10AM_TOMORROW < 1 days 
// instead of check block.timestamp - 8AM_TODAY < 1 days
```

2023-01-11 09:59 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
I think we should design the contract in such a way that pause periods for changeDailyAllowance and changeResetAllowanceTime do not clash

2023-01-11 10:54 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
maybe can take a quick look at some WIP in this branch I did two days ago: https://github.com/WavesHQ/bridge/tree/cuong/reset-passing-timestamp

2023-01-12 03:07 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
`_newResetEpoch` & `notInChangeAllowancePeriod == true` can not be in same time frame. Is this what you are referring to?

2023-01-12 03:38 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
you mean inChangeAllowancePeriod == true? 
Anw, yes, I think smart contract should check for that

2023-01-12 03:59 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetEpoch) external {
Yes, I agree. We should have this check. Are you adding it as part of your PR?

2023-01-13 04:30 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        uint256 resetEpoch;
Wondering if this can be re-named for clarity, since this is more of a `timestamp` and [is definitely not an `epoch`](https://info.etherscan.com/epoch-in-ethereum/#:~:text=In%20Ethereum%2C%20an%20epoch%20is,6.4%20minutes%20in%20total%20time.) 

I'm thinking `lastResetAt`, `lastResetAtTimestamp`, or `latestResetTimestamp`. WDYT?

2023-01-13 06:45 UTC, weiyuan95 requested changes

2023-01-13 06:45 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetTimeStamp) external {
Looking at this, my main worry is that this can potentially cause some unexpected behaviour, and could introduce potential bugs since we have two ways of modifying the state of the `tokenAllowance`. This puts the stress on the devs to ensure that we've covered all the possible states and account for them so that we don't introduce potential attack vectors.

I would suggest that we merge `changeDailyAllowance` and `changeResetAllowanceTime` to one function, `changeTokenAllowance(address _tokenAddress, uint256 _newResetTimestamp, uint256 _dailyAllowance)`. 

With this, the `_newResetTimestamp` essentially controls when the token is active again, and will reject with an appropriate error if `block.timestamp < _newResetTimestamp`.

This simplifies the logic, and we would not need an `inChangeAllowancePeriod` modifier anymore since it's fully controlled from `_newResetTimestamp`?

2023-01-13 07:25 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function changeResetAllowanceTime(address _tokenAddress, uint256 _newResetTimeStamp) external {
As discussed on the call. I'm working on changing the requirements. This might take longer as tests need to be change. Also,  bridging need to tested without  inChangeAllowancePeriod`.

2023-01-16 04:49 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (tokenAllowancesStartTime > block.timestamp)
Most of them are replacing the traditional require statement for us, resulting in less opcodes.

2023-01-16 07:34 UTC, weiyuan95 requested changes
Some minor comments. If changing `modifier inChangeAllowancePeriod` causes a lot of bloat to this PR, let's leave it for another one.

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        if (tokenAllowances[_tokenAddress].latestResetTimestamp + (1 days) > block.timestamp) {
```suggestion
        require(amount > 0);
        // Transaction is within the last tracked day's daily allowance
        if (tokenAllowances[_tokenAddress].latestResetTimestamp + (1 days) > block.timestamp) {
```

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
>          tokenAllowances[_tokenAddress].inChangeAllowancePeriod = false;
We don't need this as well since we don't need to track it anymore.

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
>        await time.increase(60 * 60 * 24);
Can I verify the expected behaviour here?
1. The token is supposed to be active 2 days in the future.
2. Trying to bridge a transaction causes a revert with STILL_IN_CHANGE_ALLOWANCE_PERIOD
3. 1 day has passed, and `bridgeToDeFiChain` is called again.
4. The revert is now `EXCEEDS_DAILY_ALLOWANCE`

Shouldn't it be `STILL_IN_CHANGE_ALLOWANCE_PERIOD`? 🤔 Since `block.timestamp < tokenAllowanceStartTime` should be `true`

If this test was passing unexpectedly, let's figure out why as well.

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
> +        await expect(proxyBridge.changeDailyAllowance(testToken.address, toWei('10'), currentTimeStamp(60 * 60 * 25)))
I would set `const currentTime = currentTimeStamp(60 * 60 * 25)`, then use the variable `currentTime` in the expectations.

You never know when the test might suddenly fail because the timestamps are 1ms off 🤣 . This applies to any kind of expectations like this as well where we are expecting 2 timestamps to be the same.

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +  timeStamp?: number,
```suggestion
  additionalTime?: number,
```

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, testToken.address, 0, { value: toWei('10') }),
If `value: ` here does not matter, let's remove it to remove any possible confusion?

2023-01-16 07:34 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      // Contract address should be Zero
```suggestion
      // Contract address balance should be zero
```

2023-01-16 09:18 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
>          tokenAllowances[_tokenAddress].inChangeAllowancePeriod = false;
I'm not sure what state var you talking about.

2023-01-16 10:05 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
>          tokenAllowances[_tokenAddress].inChangeAllowancePeriod = false;
Ah sorry, this comment is confusing because it's not a change of this PR.

 I mean we don't need `inChangeAllowancePeriod` anymore since we don't use it anywhere anmore

2023-01-17 07:55 UTC, weiyuan95 requested changes
Few more minor changes, then we're good to go!

2023-01-17 07:55 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * @param newTimeStamp The new timeStamp of the supported toke
```suggestion
     * @param previousTimeStamp The old reset timeStamp of the supported token that is being replaced
     * @param newTimeStamp The new reset timeStamp of when the supported token starts to be supported
```

2023-01-17 07:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
>        it('Successfully emitted event when changing allowances', async () => {
We should test the failure scenarios when changing allowances as well for the reset time, I don't see it being tested anywhere
```
        if (_newResetTimeStamp - block.timestamp <= 1 days) revert INVALID_RESET_EPOCH_TIME();
```

2023-01-17 07:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +        // Daily allowance set to 10. This tx should fail
```suggestion
        // Daily allowance set to 15 during setup. This tx should fail (8 + 7 + 2) > 15
```

2023-01-17 07:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      ).to.reverted;
According to [the docs](https://hardhat.org/hardhat-chai-matchers/docs/overview#reverts), this should be `to.be.reverted`, let's double check this everywhere!

2023-01-17 07:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/testUtils/mathUtils.ts
> +export function currentTimeStamp(additionalTime?: number): number {
tbh, this should look more like
```ts
function getCurrentTimeStamp({ additionalTime } : GetTimestampOptions): number {...}

interface GetTimestampOptions {
  additionalTime?: number
}
```

So that we can make a cleaner function call like 
```ts
getCurrentTimeStamp({additionalTime: 60 * 60 * 24})
```

but that is a minor thing that belongs to another PR

2023-01-17 08:16 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      ).to.reverted;
`to.reverted` and `to.be.reverted` can be used interchangeably. I will change it to to.be.reverted`

2023-01-17 08:45 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/testUtils/mathUtils.ts
> +export function currentTimeStamp(additionalTime?: number): number {
Okay, I will change this on another PR.

2023-01-17 08:46 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.dailyAllowance.spec.ts
>        it('Successfully emitted event when changing allowances', async () => {
Done

2023-01-17 09:15 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      ).to.reverted;
Ah, really? Their docs aren't up to date then 🤣

2023-01-17 09:34 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.evmToDefi.spec.ts
> +      ).to.reverted;
Yes, As per my research. There isn't much difference.

2023-01-17 10:01 UTC, weiyuan95 approved these changes

2023-01-17 10:02 UTC, merged