Cuong/proxytest
WavesHQ/bridge pull request #178
Opened 2023-01-10 15:27 UTC by cuongquangnam

#### What this PR does / why we need it:
Add tests for upgrading Bridge to a new version
Resolve this [PR](https://github.com/WavesHQ/bridge/issues/162)

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-11 09:26 UTC, Abhishekkochar requested changes

2023-01-11 09:26 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      let tx = await testToken.mint(proxyBridge.address, 100);
We should remove the `let tx`. Keep this consistent through all tests

2023-01-11 09:26 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      tx = await proxyBridge.upgradeTo(newImplementation.address);
As mentioned above.

2023-01-11 09:26 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        value: ethers.utils.parseEther('1.0'),
Please use toWei()

2023-01-11 09:26 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      const tx = await proxyBridge.addSupportedTokens(ethers.constants.AddressZero, 15);
`15` should be `toWei('15')`

2023-01-13 03:33 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/NewImplementation.sol
> +// Inheritance chain is the same as the old version so that the state variables storage slots follow the same order
Is this necessary and something that we need to ensure for upgraded contracts in the future? What do we need to take note of so that we do not run into problems with the storage slots?

2023-01-13 03:36 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/NewImplementation.sol
> +    mapping(address => uint256) public eoaAddressToNonce;
Do these need to be declared in this exact order as well? 😅

2023-01-13 03:55 UTC, weiyuan95 requested changes

2023-01-13 03:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      console.log('before ', blockNum);
Let's remove these logs. IMO we don't need to test that the contracts have been successfully deployed since your expectations below will fail if they aren't deployed.

If it's for something else, then let's write a proper expectation like `expect(beforeBlockNumber.lt(afterBlockNumber)).toBeTrue()`

2023-01-13 03:55 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      let tx = await testToken.mint(proxyBridge.address, 100);
Yep, let's be more descriptive with these instead of reusing `tx` everywhere. This can be `mintTokenTx` for example

2023-01-13 03:57 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +            '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',
Where does this come from? 🤔

2023-01-13 04:19 UTC, weiyuan95 requested changes

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    it('Call a method that is not in the implementation interface', async () => {
```suggestion
    it('should revert when calling a method that is not in the implementation interface', async () => {
```

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    it('Send no data and send some ether to the smart contract', async () => {
```suggestion
    it('should increase bridge balance when sending no data and ether to the smart contract', async () => {
```

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await defaultAdminSigner.sendTransaction({
Any particular reason why we are sending transactions this way instead of doing something like `BridgeV1.attach(proxyBridge.address).connect(defaultAdminSigner).addSupportedTokens(...)` 

That way we have strongly typed method calls and it's clearer as well instead of doing native transactions, and it's also still being proxied through the `proxyBridge`, just that we rely on the `BridgeV1` interface in code.

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      ).to.reverted;
```suggestion
      ).to.be.reverted;
```
Is it this instead? 🤔

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      const bridgeDeploymentResult: BridgeDeploymentResult = await loadFixture(deployContracts);
```suggestion
      const bridgeDeploymentResult = await loadFixture(deployContracts);
```
The return type can be inferred from the function

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    let abiCoder: any;
```suggestion
    let abiCoder: AbiCoder;
```

You'll need to make the appropriate import as well.

2023-01-13 04:19 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
Hmm, this should not work right? We should not be allowing `0` values? 🤔

2023-01-13 05:54 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/NewImplementation.sol
> +// Inheritance chain is the same as the old version so that the state variables storage slots follow the same order
Storage layout of smart contracts using inheritance follow the C3 Linearization. 
https://en.wikipedia.org/wiki/C3_linearization
So currently, by using tool like [surya](https://github.com/ConsenSys/surya), we can trace the C3 Linearization of BridgeV1 as follows: 
BridgeV1
  ↖ AccessControlUpgradeable
  ↖ ERC165Upgradeable
  ↖ IERC165Upgradeable
  ↖ IAccessControlUpgradeable
  ↖ ContextUpgradeable
  ↖ EIP712Upgradeable
  ↖ UUPSUpgradeable
  ↖ ERC1967UpgradeUpgradeable
  ↖ Initializable
  ↖ IERC1822ProxiableUpgradeable

The compiler will allocate slots from the bottom of the above chain to the top of the chain (in our case, because IERC1822ProxiableUpgradeable does not have any state variable, the first slot will belong to Initializable contract)

2023-01-13 06:27 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/NewImplementation.sol
> +    mapping(address => uint256) public eoaAddressToNonce;
Yes, you can refer to these: 
https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies
https://docs.soliditylang.org/en/v0.8.17/internals/layout_in_storage.html

2023-01-13 06:31 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +            '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ac30219a6a0eb9f98798da39ddef7fe554e43616/contracts/proxy/ERC1967/ERC1967Upgrade.sol#L28

2023-01-13 06:33 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      let tx = await testToken.mint(proxyBridge.address, 100);
oh, I think @Abhishekkochar wants to remove the use of tx.wait(), which is fine given the transactions sent out in tests seem to get executed instantly. Made changes in my new commit

2023-01-13 06:37 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +            '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',
BridgeV1 inherits from ERC1967UpgradeUpgradeable, which is upgradeable version of the above contract.
(https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.8.0/contracts/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol)

2023-01-13 06:56 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +            '0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc',
Let's put that as a comment!

2023-01-13 08:57 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
We allow in the current contract

2023-01-13 09:58 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
Definitely should be fixed. @Abhishekkochar can you double check this, and if it's actually an issue we open an issue for it?

2023-01-13 10:04 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await defaultAdminSigner.sendTransaction({
Ok let's do it for this, and ignore the test below since it's not possible

2023-01-13 10:35 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await defaultAdminSigner.sendTransaction({
I think the point is to test different scenarios, can see the analysis in my latest commit

2023-01-13 15:16 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await expect(attachedToken.totalSupply()).to.reverted;
Can consider adding a test with a function that is non-pure, non-view and not in BridgeV1 ABI, so as to let ethers send out a transaction to the network
https://docs.ethers.org/v5/api/contract/contract/#Contract--metaclass

2023-01-16 03:40 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
In this case `0` won't be accountable. Token address is `0x0`. If we don't allow `0`, this would result in sending arb value when sending ether.

2023-01-16 04:07 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
Are you referring to the first 2 params? Understand that we have to allow `0` for the first two, but I'm referring to the value of `_amount` here, we can check and make sure that it's non-zero right?

2023-01-16 04:28 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
Tracked [here](https://github.com/WavesHQ/bridge/issues/194). Publishing as part of [PR](https://github.com/WavesHQ/bridge/pull/175)

2023-01-16 04:32 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
I meant the `_amount` As per the current code, lil change needed for this.

2023-01-16 08:15 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +        proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, ethers.constants.AddressZero, 0),
Resolving this, it is handled with `require(amount > 0)` in #175

2023-01-16 08:24 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await defaultAdminSigner.sendTransaction({
Yep, I mean using the method from the contract instance in the `Call a method that is in the implementation interface that is not payable, without sending ether` test, but using the raw calldata string for the `Revert when calling a method that is in the implementation interface that is not payable, and send ether` test since we need to send a `value` which the method call does not allow.

2023-02-02 05:22 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      await defaultAdminSigner.sendTransaction({
Hmm, I would prefer using sendTransaction in this case, as it showcases that the same method can succeed or fail with or without sending Ether. Other tests will still use the contract instance.

2023-02-05 07:51 UTC, weiyuan95 submitted a review, later dismissed
LGTM! Thanks for the work on this.

@Abhishekkochar any comments on this PR?

2023-02-06 04:55 UTC, Abhishekkochar requested changes

2023-02-06 04:55 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      proxyBridge.claimFund(accounts[2], toWei('10'), 0, ethers.constants.MaxUint256, testToken.address, signature);
```suggestion
     await proxyBridge.claimFund(accounts[2], toWei('10'), 0, ethers.constants.MaxUint256, testToken.address, signature);
```
Missing `await`

2023-02-06 04:55 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    let abiCoder: AbiCoder;
```suggestion
    const  abiCoder = new ethers.utils.AbiCoder();
```
There is no need for this in `beforeEach`

2023-02-06 04:55 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    it('Sucessful when sending no data and send some ether to the smart contract', async () => {
@weiyuan95, I suggest we wait for [PR](https://github.com/WavesHQ/bridge/pull/289) to be merged. We can then remove unneeded test for ether.

2023-02-06 06:35 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      proxyBridge.claimFund(accounts[2], toWei('10'), 0, ethers.constants.MaxUint256, testToken.address, signature);
Can probably delete this line? It has no effect on the tests (since it still passes when missing an `await`)

2023-02-06 06:40 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    it('Sucessful when sending no data and send some ether to the smart contract', async () => {
Ah. Was this to test the code below?

```
    /**
     * @dev Testing need for this fn. Using to test claim ether.
     */
    fallback() external payable {}

    /**
     * @dev Testing need for this fn. Using to test claim ether.
     */
    receive() external payable {}
```

If yes then yep, we can probably remove since we aren't worrying about ETH anymore.

2023-02-06 08:01 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +    it('Sucessful when sending no data and send some ether to the smart contract', async () => {
Yes, most of the tests here testing ether, which we aren't supporting any more.

2023-02-06 08:04 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      proxyBridge.claimFund(accounts[2], toWei('10'), 0, ethers.constants.MaxUint256, testToken.address, signature);
I believe this for checking if the `claimFund` is working properly. It is passing however not sure if the user actually received the tokens.

2023-02-07 02:14 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.proxyBehaviour.spec.ts
> +      proxyBridge.claimFund(accounts[2], toWei('10'), 0, ethers.constants.MaxUint256, testToken.address, signature);
Oh, its purpose is to test whether the nonce after the upgrade is 1 later. Anw, make changes as requested. Thanks for pointing out!

2023-02-27 02:06 UTC, closed without merging