Feat(ReadMe) - Documenting smart contracts and it's function
WavesHQ/bridge pull request #188
Opened 2023-01-12 08:28 UTC by Abhishekkochar

#### What this PR does / why we need it:
As per tittle, providing documentation on smart contracts
#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-18 07:07 UTC, weiyuan95 requested changes

2023-01-18 07:07 UTC, weiyuan95 commented on README.md
> +Both the Admin and Operational addresses can change the `_dailyAllowance` and `_newResetTimeStamp` via `changeDailyAllowance()` function. This will reset the `inChangeAllowancePeriod` to true. When t
```suggestion
Both the Admin and Operational addresses can change the `_dailyAllowance` (the new daily allowance) and `_newResetTimeStamp` (the timestamp when the token will start being supported) via `changeDailyAllowance()` function. This will reset the `inChangeAllowancePeriod` to true. When true, no bridging to the Defi chain is allowed. The allowance period stays true until it passes 24 hours since it was changed.
```

We also need to take another look at the `inChangeAllowancePeriod` part since we dont have that anymore

2023-01-18 07:07 UTC, weiyuan95 commented on README.md
> +Relayer address will primarily be used for signature.
```suggestion
The relayer address will primarily be used for verifying the signature that is signed by the server.
```

2023-01-18 07:07 UTC, weiyuan95 commented on README.md
> +Only address with admin role can change `transactionFee`. Initial fee will be set to 0.3%
```suggestion
Only address with admin role can change `transactionFee`. Initial fee will be set to 0.3%. This means that if the user bridges `X` tokens, he will only bridge 99.7% of X. The other 0.3% will be taken as fees.
```

2023-01-18 07:31 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
> +    console.log(signature);
Opps

2023-01-18 08:20 UTC, Abhishekkochar commented on README.md
> +Relayer address will primarily be used for signature.
Relayer address should be signing the signature

2023-01-19 03:15 UTC, weiyuan95 commented on README.md
> +Relayer address will primarily be used for signature.
Yep, but the concept of the 'relayer address'  exists in particular for the smart contract, and there, it's used to verify the signed claim instead of doing some form of signing.

2023-01-19 03:25 UTC, weiyuan95 requested changes
Few more nits from me 🙏🏻

2023-01-19 03:25 UTC, weiyuan95 commented on README.md
> +For the contract to spend funds on behalf of the user, the user needs to approve the smart contract with the respected ERC-20 token via the `approve()` function first.
```suggestion
For the contract to spend funds on behalf of the user, the user needs to approve the smart contract with the respective ERC-20 token via the `approve()` function first.
```

2023-01-19 03:25 UTC, weiyuan95 commented on README.md
> +Once approved, user will call the `bridgeToDeFiChain()` function with following the arguments: `_defiAddress`- address on DeFiChain that is receiving funds, `_tokenAddress` - ERC20 token's address an
```suggestion
Once approved, user will call the `bridgeToDeFiChain()` function with following the arguments: `_defiAddress` (address on DeFiChain that is receiving funds), `_tokenAddress` (ERC20 token's address) and `_amount` (amount to bridge to DeFiChain).
```

Let's be consistent with the rest of the README

2023-01-19 03:25 UTC, weiyuan95 commented on README.md
> +When sending ETHER to bridge, the user will not have to approve the contract. By default, every smart contract accepts ETH. Sending ether will be similar to ERC20, except we don't account for `_amoun
```suggestion
When sending ETHER to bridge, the user will not have to approve the contract. By default, every smart contract accepts ETH. Sending ether will be similar to ERC20, except we don't account for `_amount` and it is ignored. Instead, `msg.value()` is used. The `_defiAddress` is the address on the Defi Chain that is receiving funds. The `_tokenAddress` for ETH does not have an address, as it is a native currency. it should be identified as  `address(0)`/`0x0` instead.
```

2023-01-19 03:25 UTC, weiyuan95 commented on packages/smartcontracts/package.json
> +    "ts-node": "^10.9.1"
```suggestion
    "ts-node": "10.9.1"
```

Since we are pinning the `hardhat` version, we should pin the `ts-node` version as well to prevent potential dependency conflicts.

2023-01-19 03:25 UTC, weiyuan95 commented on README.md
> +Users will not be able to bridge more than the dailyAllowance/day.
```suggestion
Users will not be able to bridge a total amount that is more than the dailyAllowance per day.
```

2023-01-19 03:26 UTC, weiyuan95 commented on README.md
> +Both the Admin and Operational addresses can change the `_dailyAllowance` and `_newResetTimeStamp` via `changeDailyAllowance()` function. This will reset the `inChangeAllowancePeriod` to true. When t
It still mentions the `inChangeAllowancePeriod` part, we should probably delete that? 🤔

2023-01-19 11:58 UTC, weiyuan95 commented
LGTM, needs a rebase

2023-01-20 05:57 UTC, Abhishekkochar commented
> LGTM, needs a rebase

I will do the rebase after [PR](https://github.com/WavesHQ/bridge/pull/225).

2023-01-25 02:59 UTC, weiyuan95 requested changes

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +## Deploy ERC20 tokens 'MUSDT' & 'MUSDC'
```suggestion
### Deploy ERC20 tokens 'MUSDT' & 'MUSDC'
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +`BridgeProxy` should only need to be deployed _once_ to a blockchain. Subsequent deployments should only be deploying the implementation contract (`BridgeV2`, `BridgeV3`, etc), before calling `_upgra
```suggestion
`BridgeProxy` should only need to be deployed _once_ to a blockchain. Subsequent deployments should only be deploying the implementation contract (`BridgeV2`, `BridgeV3`, etc), before calling `upgradeTo` of the `BridgeProxy` contract.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +`ADMIN_ADDRESS`, `OPERATIONAL_ADDRESS`, `RELAYER_ADDRESS`, `TRANSACTION_FEE` & `BRIDGE_IMPLEMENTATION_ADDRESS` aka `BridgeV1` contract address.
```suggestion
Before running the above command, following `vars` need to be addressed in the script files:
`ADMIN_ADDRESS`, `OPERATIONAL_ADDRESS`, `RELAYER_ADDRESS`, `TRANSACTION_FEE` & `BRIDGE_IMPLEMENTATION_ADDRESS` (aka the `BridgeV1` contract address).
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +Both the Admin and Operational addresses can change the `_dailyAllowance` (the new daily allowance) and `_newResetTimeStamp` (the timestamp when the token will start being supported) via `changeDaily
```suggestion
Both the Admin and Operational addresses can change the `_dailyAllowance` (the new daily allowance) and `_newResetTimeStamp` (the timestamp when the token will start being supported) via the `changeDailyAllowance()` function. The changes will only come into effect when the current timestamp has reached the `_newResetTimeStamp`. This new timestamp will have to be at least 24 hours in the future, if not the function will revert with `INVALID_RESET_EPOCH_TIME`

During this 'change in allowance' period, no bridging to DeFiChain will be allowed. However, it is still possible to make additional changes by calling `changeDailyAllowance()` in case mistakes were made.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +Only addresses with Admin and operational role can call the `removeSupportedTokens()` function.
```suggestion
Only addresses with the Admin and Operational role can call the `removeSupportedTokens()` function.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +Only addresses with Admin and operational role can call the `addSupportedTokens()` function. Admin sets the `_dailyAllowance`.
```suggestion
Only addresses with the Admin and Operational role can call the `addSupportedTokens()` function. This sets the `_dailyAllowance` for a ERC20 token identified by its `_tokenAddress`. The `_startAllowanceTimeFrom` also represents when this token 'goes live'
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +User should not allow to bridge more than the dailyAllowance/day.
```suggestion
User are not allowed to bridge more than the dailyAllowance per day.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +When sending ETHER to bridge, the user will not have to approve the contract. By default, every smart contract accepts ETH. Sending ether will be similar to ERC20, except we don't account for `_amoun
```suggestion
When sending ETHER to bridge, the user will not have to approve the contract. By default, every smart contract accepts ETH. Sending ether will be similar to an ERC20 token, except we don't account for `_amount` - instead `msg.value()` is used. The `_defiAddress` is the address on the DeFiChain that is receiving funds. Since ETH does not have an address since it is the native currency, it is identified by address(0)/0x0 in `_tokenAddress`
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +### All smart contracts will be deployed on Goerli testnet.
```suggestion
All smart contracts will be deployed on Goerli testnet for testing purposes.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +Ideally, we will have multiple Test tokens available. Users will be able to mint tokens by calling the `mint()` function with the respective EOA (Externally Owned Account) or contract address and amo
```suggestion
### How to get ERC20 tokens to test bridging functionality?

The MUSDT and MUSDC contract have been deployed on Goerli for testing. Users will be able to mint tokens by calling the `mint()` function with the respective EOA (Externally Owned Account) or contract address and amount.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +To change state of any smart contract, user need to approve the smart contract with the respected token via `approve()` function first. Once approved, user will be able to bridge the token over to De
```suggestion
To change the state of any smart contract, users need to approve the smart contract of the respective token via the `approve()` function first. Once approved, user will be able to bridge the token over to DefiChain.
```

2023-01-25 02:59 UTC, weiyuan95 commented on README.md
> +`withdraw()` and `withdrawEth()` functions when called will withdraw ERC20 token and ETHER respectively. Only address with admin role can call these functions.
```suggestion
`withdraw()` and `withdrawEth()` functions when called will withdraw ERC20 token and ETHER respectively. Only the address with the Admin role can call these functions.
```

2023-01-25 03:03 UTC, weiyuan95 approved these changes
Adjusted the grammar of the documentation.

2023-01-25 03:03 UTC, merged