Feat(SmartContracts): Deployment script for Goerli test net
WavesHQ/bridge pull request #212
Opened 2023-01-18 05:32 UTC by Abhishekkochar

#### What this PR does / why we need it:
This PR introduces the deployment script for the Bridge and test tokens smart contracts

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-18 08:19 UTC, weiyuan95 commented on packages/smartcontracts/src/.env.example
> +PRIVATE_KEY = '123test123test123test123test123test123test123test'
How do we provide a private key for this, if we use a wallet like metamask?

2023-01-18 08:21 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
What is this `gasPrice` for?

2023-01-18 08:22 UTC, weiyuan95 requested changes
Some quick comments, the rest LGTM for now, will do a more detailed review later.

CI is failing as well, i'm guessing you have dotenv installed globally. Need to add it to the package.json

2023-01-18 08:25 UTC, Abhishekkochar commented on packages/smartcontracts/src/.env.example
> +PRIVATE_KEY = '123test123test123test123test123test123test123test'
Private key will be stored in `.env`. We will be using a script instead of using MetaMask. We can use MetaMask if using  remix.

2023-01-18 08:27 UTC, Abhishekkochar commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
This is for the tx. If the `gasPrice` is too low, tx will get stuck in Mempool.

2023-01-18 08:29 UTC, Abhishekkochar commented
> Some quick comments, the rest LGTM for now, will do a more detailed review later.
> 
> CI is failing as well, i'm guessing you have dotenv installed globally. Need to add it to the package.json

Already on it.

2023-01-19 02:55 UTC, weiyuan95 commented on packages/smartcontracts/src/.env.example
> +PRIVATE_KEY = '123test123test123test123test123test123test123test'
Ah. I was referring to [this](https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-export-an-account-s-private-key) but I found it after a quick google 🤣

2023-01-19 03:11 UTC, Abhishekkochar commented on packages/smartcontracts/src/.env.example
> +PRIVATE_KEY = '123test123test123test123test123test123test123test'
Oh ya hahah. That's how I do it as well.

2023-01-19 04:12 UTC, Abhishekkochar commented on packages/smartcontracts/src/.env.example
> +PRIVATE_KEY = '123test123test123test123test123test123test123test'
I have added the above link in .env.example

2023-01-19 06:45 UTC, weiyuan95 requested changes
One last quick point 😬

2023-01-19 06:45 UTC, weiyuan95 commented on README.md
> +Devs need to deploy the `BridgeV1` contract contract before the `BridgeProxy`.
```suggestion
Devs need to deploy the `BridgeV1` implementation contract before the `BridgeProxy`.

`BridgeProxy` should only need to be deployed _once_ to a blockchain. Subsequent deployments should only be deploying the implementation contract (`BridgeV2`, `BridgeV3`, etc), before calling `_upgradeTo` of the `BridgeProxy` contract.

This follows the [proxy pattern](https://blog.openzeppelin.com/proxy-patterns/), with the behaviour being inherited from `OpenZeppelin` proxy contracts.
```

Looking at this, I realised that we have not exposed `_upgradeTo` on `BridgeProxy` yet, but I'm guessing that will be part of #159

2023-01-19 07:55 UTC, Abhishekkochar commented on README.md
> +Devs need to deploy the `BridgeV1` contract contract before the `BridgeProxy`.
https://goerli.etherscan.io/address/0x93fE70235854e7c97A5db5ddfC6eAAb078e99d3C#writeProxyContract. I have Updated the proxy pattern (will now show as proxy as contract.) We can upgrade this anytime as long as it's satisfy `onlyProxy`.

2023-01-19 08:11 UTC, weiyuan95 commented on README.md
> +Devs need to deploy the `BridgeV1` contract contract before the `BridgeProxy`.
Hmm, i'm not sure what you mean. We have 2 proxy contracts now?

https://goerli.etherscan.io/address/0x93fE70235854e7c97A5db5ddfC6eAAb078e99d3C#readProxyContract 
https://goerli.etherscan.io/address/0x50894DE4589BaC6FBA9D77e3c988Ff5594E6710A#readProxyContract

They both look the same to me 🤔 . Also, I thought that we had to expose `_upgradeTo` since it's currently an internal method.

We can handle those issues in other PRs though, will merge this in first so that we can work on the utility and fixture scripts for UI devs.

2023-01-19 08:11 UTC, merged

2023-01-19 11:49 UTC, weiyuan95 commented on README.md
> +Devs need to deploy the `BridgeV1` contract contract before the `BridgeProxy`.
Update to this
- `upgradeTo` is already handled in one of the open zep contract the bridge implements
- The other proxy contract was probably from Cuong testing the deployment