feat(ui-ux): add initial smart contract integration for EVM to DFC transfer
WavesHQ/bridge pull request #232
Opened 2023-01-25 06:51 UTC by lykalabrada

#### What this PR does / why we need it:
Allows user to successfully bridge funds from EVM to DeFiChain using Goerli testnet

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-27 01:55 UTC, thedoublejay requested changes

2023-01-27 01:55 UTC, thedoublejay commented on apps/web/src/components/ConfirmTransferModal.tsx
> +              Funds will be transferred to your DefiChain wallet shortly.
```suggestion
              Funds will be transferred to your DeFiChain wallet shortly.
```

2023-01-27 01:55 UTC, thedoublejay commented on apps/web/src/components/ConfirmTransferModal.tsx
> +          suffix=" DFI" // TODO: Create hook to get fee based on source/destination
We have something similar on LW, I think we can use that

2023-01-27 01:55 UTC, thedoublejay commented on apps/web/src/components/ConfirmTransferModal.tsx
> +        <div>
Can you add a TODO here to link this to Scan once available?

2023-01-27 01:55 UTC, thedoublejay commented on apps/web/src/layouts/contexts/ContractContext.tsx
> +    if (networkEnv === NetworkEnvironment.mainnet) {
We can simplify it to a variable, so we just call setConfig once

2023-01-27 11:46 UTC, lykalabrada commented on apps/web/src/components/ConfirmTransferModal.tsx
> +          suffix=" DFI" // TODO: Create hook to get fee based on source/destination
I have added, followed the one we have on LW

2023-01-30 01:24 UTC, thedoublejay requested changes

2023-01-30 01:24 UTC, thedoublejay commented on apps/web/cypress/e2e/bridge.spec.ts
> +describe.only("Test User Login", () => {
```suggestion
describe("Test User Login", () => {
```

2023-01-31 04:06 UTC, thedoublejay approved these changes

2023-01-31 04:06 UTC, merged