feat(Contracts): Local and Mainnet deployment scripts
WavesHQ/bridge pull request #242
Opened 2023-01-26 07:25 UTC by Abhishekkochar

#### What this PR does / why we need it:
This fixes the current hardhat task issue. Two instance of the contracts were getting deployed when running the hardhat task. User can run the following command to mint mock tokens and approve the proxy contract `npx hardhat run --network hardhat ./scripts/localContractsDeployment.ts`

This will only work on localhost/hardhat
#### Which issue(s) does this PR fixes?:

Fixes #236 

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-27 04:06 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
Is this necessary instead of letting this value be automatically decided? Or is this just to expedite the deployment? 🤔

2023-01-27 04:15 UTC, Abhishekkochar commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
We can let this be as it is. In some scenarios, we will need to set higher gas price if the network is congested.

2023-01-27 04:49 UTC, weiyuan95 requested changes
Some quick comments. The package's README.md will also need to be changed to account for using the script instead of the hardhat task.

2023-01-27 04:49 UTC, weiyuan95 commented on packages/smartcontracts/src/scripts/deployBridgeProxy.ts
> +  BridgeV1Address: string;
```suggestion
  adminAddress: string;
  operationalAddress: string;
  relayerAddress: string;
  bridgeV1Address: string;
```

2023-01-27 04:49 UTC, weiyuan95 commented on packages/smartcontracts/src/scripts/deployERC20.ts
> +interface TestTokenAddress {
```suggestion
interface TestTokens {
```

2023-01-27 04:49 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/LocalTest.spec.ts
> +});
```suggestion
describe('SetupLocalTestTask', () => {
  it('should set up the expected local testnet state', async () => {
    // Given that the setupLocalTest task is run
    const { usdtContract, usdcContract, bridgeProxy } = await mintAndApproveTestTokensLocal();

    const expectedTimeStamp = Math.floor(Date.now() / 1000);

    // suppressing type error - method is actually properly typed
    // @ts-ignore
    const [adminSigner, operationalSigner] = await ethers.getSigners();
    const adminAddress = adminSigner.address;
    const operationalAddress = operationalSigner.address;

    const musdtContract = TestToken__factory.connect(usdtContract.address, adminSigner);
    const musdtAddress = musdtContract.address;
    const musdcContract = TestToken__factory.connect(usdcContract.address, adminSigner);
    const musdcAddress = musdcContract.address;
    // behind proxy, so we need to use the proxy address
    const proxyBridge = BridgeV1__factory.connect(bridgeProxy.bridgeProxy.address, adminSigner);

    // When checking the ERC20 balances of the EOA
    expect(await musdtContract.balanceOf(adminAddress)).to.equal(toWei('100000'));
    expect(await musdcContract.balanceOf(adminAddress)).to.equal(toWei('100000'));
    // When checking the admin address of the bridge
    // Then the EOA account should have the admin role.
    const DEFAULT_ADMIN_ROLE = '0x0000000000000000000000000000000000000000000000000000000000000000';
    expect(await proxyBridge.hasRole(DEFAULT_ADMIN_ROLE, adminAddress)).to.equal(true);

    // When checking the operational address of the bridge
    // Then the EOA account should have the operational role.
    const OPERATIONAL_ROLE = ethers.utils.solidityKeccak256(['string'], ['OPERATIONAL_ROLE']);
    expect(await proxyBridge.hasRole(OPERATIONAL_ROLE, operationalAddress)).to.equal(true);

    // When checking that MUSDT is supported on the bridge
    // Then the token should be supported
    expect(await proxyBridge.supportedTokens(musdtAddress)).to.equal(true);
    const musdtSupportedTokenInfo = await proxyBridge.tokenAllowances(musdtAddress);

    // And the token should have the expected reset time
    expect(musdtSupportedTokenInfo[0].eq(expectedTimeStamp)).to.equal(true);

    // And the token should have the expected daily allowance
    expect(musdtSupportedTokenInfo[1].eq(ethers.constants.MaxInt256)).to.equal(true);

    // When checking that MUSDC is supported on the bridge
    // Then the token should be supported
    expect(await proxyBridge.supportedTokens(musdcAddress)).to.equal(true);
    const musdcSupportedTokenInfo = await proxyBridge.tokenAllowances(musdcAddress);

    // And the token should have the expected reset time
    expect(musdcSupportedTokenInfo[0].eq(expectedTimeStamp)).to.equal(true);

    // And the token should have the expected daily allowance
    expect(musdcSupportedTokenInfo[1].eq(ethers.constants.MaxInt256)).to.equal(true);

    // When checking that bridgeToDeFiChain can be called with a MUSDT token
    // And provisioning the necessary approval
    await musdtContract.approve(proxyBridge.address, ethers.constants.MaxInt256);

    // Then the call should not revert
    await proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, musdtAddress, 1);

    // And the EOA's balance of MUSDT should be reduced by 1
    expect((await musdtContract.balanceOf(adminAddress)).eq(999_999_999)).to.eq(true);

    // When checking that bridgeToDeFiChain can be called with a MUSDC token
    // And provisioning the necessary approval
    await musdcContract.approve(proxyBridge.address, ethers.constants.MaxInt256);

    // Then the call should not revert
    await proxyBridge.bridgeToDeFiChain(ethers.constants.AddressZero, musdtAddress, 1);

    // And the EOA's balance of MUSDT should be reduced by 1
    expect((await musdcContract.balanceOf(adminAddress)).eq(999_999_999)).to.eq(true);
  });
});
```

IMO this is the ideal test case that we should aim towards since we want to add the tokens support for the devs as well. I think we'll need to make the changes in `localContractsDeployment.ts` to account for it.

2023-01-27 04:51 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
This is [paying almost double](https://etherscan.io/gastracker) of the current gas price, but since it's a one time thing i'm not too concerned 🤣 . Would rather get the contract deployed.

2023-01-27 07:03 UTC, Abhishekkochar commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
<img width="1045" alt="Screenshot 2023-01-27 at 3 01 11 PM" src="https://user-images.githubusercontent.com/43106142/215027883-acba21f4-60aa-47fa-93f4-600dafda6099.png">
This is the deployment cost for current SMs.

2023-01-27 07:22 UTC, weiyuan95 requested changes

2023-01-27 07:22 UTC, weiyuan95 commented on README.md
> +Devs can change these addresses as per their requirements in `../scripts/localContractsDeployment.ts` file.
Would shift this section to `packages/smartcontracts/README.md` since it does not really concern the Bridge repo as a whole and can be scoped to the package.

2023-01-27 07:22 UTC, weiyuan95 commented on packages/smartcontracts/src/scripts/localContractsDeployment.ts
> +  const bridgeImplementationContract = bridgeV1.attach(bridgeProxy.address);
We should be logging
- The EOA address that receives the funds (ie. signers[0].address) so that it's easy for the devs to know what address to use
- The address of the proxy that the UI should interact with

2023-01-27 07:22 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +      gasPrice: 30000000000, // this is 30 Gwei
Are those the units of gas used?

But ok, we can review the gas price again before deploying to mainnet

2023-01-27 08:32 UTC, weiyuan95 commented on packages/smartcontracts/README.md
> -1. In your terminal, run `npx hardhat --config ./src/hardhat.config.ts node` from this package's directory
We still need to leave this in so that people will know how to start a node 😅

2023-01-27 08:50 UTC, Abhishekkochar commented on packages/smartcontracts/README.md
> -1. In your terminal, run `npx hardhat --config ./src/hardhat.config.ts node` from this package's directory
We don't need to start a node for this.  This can be done without running the node first

2023-01-30 04:36 UTC, weiyuan95 commented on packages/smartcontracts/README.md
> -1. In your terminal, run `npx hardhat --config ./src/hardhat.config.ts node` from this package's directory
Running just the script as is, there won't be a node available at `localhost:8545` right? 🤔 That's what I remember from running the task previously.

ie. If i just run `npx hardhat run --network hardhat ./scripts/localContractsDeployment.ts`, I can't actually access the local net?

2023-01-30 04:44 UTC, weiyuan95 commented on packages/smartcontracts/src/scripts/localContractsDeployment.ts
> +  const bridgeImplementationContract = bridgeV1.attach(bridgeProxy.address);
Think this is still missing, you didn't add the necessary `console.log`s

2023-01-30 05:19 UTC, Abhishekkochar commented on packages/smartcontracts/README.md
> -1. In your terminal, run `npx hardhat --config ./src/hardhat.config.ts node` from this package's directory
Yes, you are right. I was thinking from the test perspective. Fixed

2023-01-30 05:31 UTC, Abhishekkochar commented on packages/smartcontracts/README.md
> -1. In your terminal, run `npx hardhat --config ./src/hardhat.config.ts node` from this package's directory
When switching to localHost in metamask, TestToken addresses are invalid. Investigating this for now.

2023-01-30 09:00 UTC, lykalabrada commented on packages/smartcontracts/src/scripts/localContractsDeployment.ts
> +  const bridgeImplementationContract = bridgeV1.attach(bridgeProxy.address);
Hello @Abhishekkochar It's working fine on my end, but as mentioned by @weiyuan95 please also log bridge proxy address. . Thank you!

2023-01-30 10:08 UTC, lykalabrada submitted a review, later dismissed
Tested from my end, works fine 👍

2023-01-30 10:38 UTC, weiyuan95 approved these changes
Approving after applying some code suggestions

2023-01-30 11:22 UTC, lykalabrada approved these changes

2023-01-30 12:08 UTC, merged