feature(ui-ux): transaction flow for DFI to ERC20
WavesHQ/bridge pull request #247
Opened 2023-01-27 07:19 UTC by chloezxyy

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-30 04:50 UTC, lykalabrada requested changes

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> +            onClick={goToNextStep}
Please add a `TODO` here to save this return address to the localstorage. We'll have to move the entire saving of unconfirmed txn on this part too

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> +        <div className="absolute md:bottom-[202px] md:left-[180px] hidden md:block">
Need to add space here
![image](https://user-images.githubusercontent.com/17063281/215383890-5a1b4d05-f80e-4ecc-9d43-10c941f2e24b.png)

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> +        <span className="font-semibold tracking-wider text-dark-900">
Let's follow the letter-spacing mentioned in figma

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepOneInitiate.tsx
> +      </div>
Need to add this message when address is empty/invalid:
![image](https://user-images.githubusercontent.com/17063281/215387240-08ffa1de-f6ef-4cc5-b537-acafeeb4335e.png)

Please also check the space on the sides, it looks smaller than the design

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                  // onTimeElapsed={() => {}}
Please remove

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +          are irreversible. For more details, read FAQs and terms of use.
We can link `FAQs and terms of use` to `/faqs` for now

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/TimeLimitCounter.tsx
> +      <span className="text-xs md:text-sm font-semibold tracking-wide text-dark-1000 items-center flex justify-center">
Can you also help update this time remaining text? Follow the updated one in figma 🙏

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +// TODO: @chloe rename to steptwo
We can remove this TODO now :)

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepLastClaim.tsx
> +    <div className={clsx("mt-14 px-6", "md:mt-4 md:px-[73px] md:py-6")}>
Can check again the margin top here?

2023-01-30 04:50 UTC, lykalabrada commented on apps/web/src/components/WalletAddressInputField.tsx
> +import { useEffect, useState, useRef } from "react";
Hmm lots of duplicate code from `WalletAddressInput`, can you try to extract the main component and similar logic into a separate component? then maybe we can reuse the same one

2023-01-30 15:11 UTC, chloezxyy commented on apps/web/src/components/WalletAddressInputField.tsx
> +import { useEffect, useState, useRef } from "react";
Maybe I could work around this by renaming the component so that we can use it as a generic text input field because I feel that the WalletAddressInput component has more features and the it might get quite messy with the different custom stylings that the use case requires.

2023-01-31 01:50 UTC, lykalabrada commented on apps/web/src/components/WalletAddressInputField.tsx
> +import { useEffect, useState, useRef } from "react";
Hmm but because there's a lot of address-related stuff here I think it'll be misleading to name it as a generic input field.

Would be better to just add a bit of conditional styling, we can actually use the same `<WalletAddressInput/>` and just add one prop to adjust the style for each use-case

2023-01-31 07:37 UTC, lykalabrada commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +            read FAQs and terms of use.
Please move `read` out of the link

2023-01-31 10:08 UTC, lykalabrada requested changes

2023-02-01 06:06 UTC, lykalabrada submitted a review, later dismissed

2023-02-01 08:16 UTC, lykalabrada approved these changes

2023-02-01 09:07 UTC, lykalabrada approved these changes

2023-02-01 09:07 UTC, merged