feat(EVMTransactionConfirmer): Build getAllEventsFromBlockNumber function and integration tests
WavesHQ/bridge pull request #256
Opened 2023-01-30 02:19 UTC by greggtan

#### What this PR does / why we need it:
The getAllEventsFromBlockNumber function returns an array of confirmed BRIDGE_TO_DEFI_CHAIN events from a given block number. It will be used for the backend server to bridge EVM tokens to DFC.

#### Which issue(s) does this PR fixes?:

Fixes #183

#### Additional comments: 
Currently takes in blockNumber & contractAddress as params. Will work on removing the contractAddress param by making the deployed smart contract address accessible from all files as a global variable.

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [x] Added e2e tests\*
- [ ] Added translations\*

2023-01-30 06:50 UTC, weiyuan95 commented
Writing this out here so I don't forget.

Next steps that come after this PR. These can probably be separate PRs to reduce reviewer scope.
- Last-checked block number persistence
  - Block number should not need to be passed in via an API call
  - This involves any necessary DB work that needs to be done to persist the data
- Bridge proxy address should be passed in as a config variable instead of an API call

2023-01-30 10:30 UTC, weiyuan95 requested changes

2023-01-30 11:17 UTC, lykalabrada commented on apps/server/src/AppConfig.ts
> +      address: process.env.BRIDGE_CONTRACT_ADDRESS || '',
If we are to set a config like this as environment variable, I wonder how it's possible to manage for different networks (testnet, mainnet,..).

This is a general question as I encountered something similar and had to create separate variables, something like  `goerli_contract_address, mainnet_contract_address` instead

I wonder how we'll handle different networks here 🤔

2023-01-31 02:47 UTC, weiyuan95 commented on apps/server/src/AppConfig.ts
> +      address: process.env.BRIDGE_CONTRACT_ADDRESS || '',
Great point! Since the contract addresses are immutable, the testnet contract address can actually already be hardcoded to `0x93fE70235854e7c97A5db5ddfC6eAAb078e99d3C`, and similarly for the mainnet contract when that gets deployed.

In terms of how that would look like on the `config`, something like `contracts.bridgeProxy.mainnet.address` and `contracts.bridgeProxy.testnet.address` makes sense to me (or `mainnetAddress` and `testnetAddress` if we don't care about how the 'object' looks like)

2023-01-31 09:04 UTC, Abhishekkochar commented on apps/server/src/AppService.ts
> +    const events = await contract.queryFilter(eventSignature, blockNumber, currentBlockNumber - 65);
@greggtan,general question, is there a specific reason why we decide on checking past 65 blocks?

2023-01-31 10:31 UTC, eli-lim commented on apps/server/src/AppService.ts
> +      this.configService.getOrThrow('contract.address'),
This should be sourced in the constructor instead, so if the contract address doesn't exist, then the app can fail start-up (we prefer early exits instead of silent time-bombs in production)

2023-01-31 10:31 UTC, eli-lim commented on apps/server/src/AppConfig.ts
> +      address: process.env.BRIDGE_CONTRACT_ADDRESS || '',
this shouldn't default to an empty string - it should either be a valid address or `undefined`

2023-02-01 01:54 UTC, greggtan commented on apps/server/src/AppService.ts
> +    const events = await contract.queryFilter(eventSignature, blockNumber, currentBlockNumber - 65);
Following issue 183 (https://github.com/WavesHQ/bridge/issues/183) by @weiyuan95, we will wait for 65 confirmations, unless we want to wait be speedier at the expense of some security. In that case, we will go with 33 confirmations!

This number is definitely flexible and will depend on discussion.

2023-02-01 04:23 UTC, Abhishekkochar reviewed
Everything else LGTM.

2023-02-01 04:23 UTC, Abhishekkochar commented on apps/server/test-i9n/BridgeApp.i9n.ts
> +  static register(config: AppConfig): DynamicModule {
It would be best to have `TestingExampleModule` in separate file as it being used in different files.

2023-02-01 04:23 UTC, Abhishekkochar commented on apps/server/test-i9n/BridgeApp.i9n.ts
> +export function buildTestConfig(startedHardhatContainer: StartedHardhatNetworkContainer, contractAddress?: string) {
Same as above. We can also do strongly type return 
```suggestion
export function buildTestConfig(startedHardhatContainer: StartedHardhatNetworkContainer, contractAddress?: string) : AppConfig {....
```

2023-02-01 05:39 UTC, cuongquangnam commented on apps/server/src/AppService.ts
> +      this.configService.getOrThrow('contract.bridgeProxy.testnetAddress'),
Why does it have to be a testnet address over here? Can it be a mainnet address?

2023-02-01 06:44 UTC, weiyuan95 commented on apps/server/src/AppService.ts
> +      this.configService.getOrThrow('contract.bridgeProxy.testnetAddress'),
Clarified with Vir. The UI will support both test and main net transactions, so we'll need to poll both. Creating a service that's specifically doing that will come in another PR though.

2023-02-01 07:16 UTC, weiyuan95 requested changes

2023-02-01 07:16 UTC, weiyuan95 commented on apps/server/test-i9n/BridgeApp.i9n.ts
> +    evmContractManager = hardhatNetwork.contracts;
These test fixtures (ie setting up the bridge contracts) can sit in something like a `BridgeAppTesting` class to be DRY, but that is an improvement that can come in a separate PR. Let's get the baseline out first.

2023-02-01 07:16 UTC, weiyuan95 commented on apps/server/test-i9n/defichain/wallet.i9n.ts
> +    testing = new BridgeServerTestingApp(TestingExampleModule.register(buildTestConfig(startedHardhatContainer, '')));
```suggestion
    testing = new BridgeServerTestingApp(TestingExampleModule.register(buildTestConfig(startedHardhatContainer)));
```

Since it's optional, we don't need to pass it in. Same for the other test.

2023-02-01 07:16 UTC, weiyuan95 commented on apps/server/test-i9n/BridgeApp.i9n.ts
> +export function buildTestConfig(startedHardhatContainer: StartedHardhatNetworkContainer, contractAddress?: string) {
Another thing, since i'm guessing this test config will only get larger (postgres, etc), with different types, I would prefer that this is as explicit as possible with what users need to pass in. And ideal function call would be

```ts
buildTestConfig({
  hardhatContainer: startedHardhatContainer,
  bridgeProxyAddress: 'some_address',
  ...
})
```
This way it clear (something like named params) on what people need to pass in to build the test config.

2023-02-02 03:28 UTC, weiyuan95 approved these changes
Merging this in first as a first-cut baseline. Follow up tasks from comments [here](https://github.com/WavesHQ/bridge/issues/281)

2023-02-02 03:28 UTC, merged