docs(ReadMe):Updated readMe with add and remove funds sections
WavesHQ/bridge pull request #267
Opened 2023-01-31 10:48 UTC by Abhishekkochar

#### What this PR does / why we need it:
As per the title, Added sections for sending and removing funds on bridge contract. 
There is also an guide on how to add owners to gnosis safe .
#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-01-31 10:49 UTC, Abhishekkochar commented on README.md
> +### Add funds
@cuongquangnam , can you please quickly double check this?

2023-02-01 02:28 UTC, cuongquangnam commented on README.md
> +Funding the bridge contract would ideally be done on lunch (Not decided on specific numbers)
on launch right, at first sight, I thought we gonna do funding while eating

2023-02-01 02:29 UTC, cuongquangnam commented on README.md
> +Admins can send the ETHER and ERC20 tokens via the `transfer(address _to, uint256 _amount)` function.
for the case of ether, it will be a simple transfer in metamask

2023-02-01 03:24 UTC, Abhishekkochar commented on README.md
> +Funding the bridge contract would ideally be done on lunch (Not decided on specific numbers)
oh that's one of a kind typo hahaha

2023-02-01 03:24 UTC, Abhishekkochar commented on README.md
> +Admins can send the ETHER and ERC20 tokens via the `transfer(address _to, uint256 _amount)` function.
Yes, however the underlying function will be `transfer` regardless of ETHER and ERC20 via metamask

2023-02-02 03:45 UTC, weiyuan95 requested changes

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +## Fund Bridge with ETHER and ERC20 tokens
There's no more ETH, only wETH 😛

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +Anyone can send fund to the bridge contract, ideally in this case, this should be done by liquidity providers. If tokens send by other addresses straight to the contract, those tokens will be unaccou
```suggestion
Anyone can send funds to the bridge contract. Ideally, this should be done by liquidity providers. If there are tokens sent by other addresses to the contract, those tokens will be unaccounted for.
```

Removing the part about processing refunds. Such cases will be the exception - not the norm.

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +Admins can send the ETHER and ERC20 tokens via the `transfer(address _to, uint256 _amount)` function or utilizing wallet such as Metamask.
```suggestion
Admins can send the ERC20 tokens via the `transfer(address _to, uint256 _amount)` function or utilizing wallets such as Metamask.
```

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +Funding the bridge contract would ideally be done upon launch (Not decided on specific numbers)
```suggestion
```

No need to mention this!

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +ETHER and ERC20 can be withdrawn by the Admin address only via `withdrawEth(uint256 amount)` and `withdraw(address _tokenAddress, uint256 amount)` functions respectively.
```suggestion
### Withdrawing funds

ERC20 tokens can be withdrawn by the Admin address only via the `withdraw(address _tokenAddress, uint256 amount)` function.
```

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +ETHER and ERC20 can be withdrawn by the Admin address only via `withdrawEth(uint256 amount)` and `withdraw(address _tokenAddress, uint256 amount)` functions respectively.
This will need to be updated when #277 implementation is added.

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +Admin and Operational addresses will be Gnosis safes, ideally will be with at least 3 owners. In case of 3 addresses, 2 approval ( this can be set when making a safe or later ) will be needed to exec
```suggestion
Admin and Operational addresses will be Gnosis safes, ideally will be with at least 3 owners with a 2/3 quorum.
```

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +More admins can be added later, for more info [Gnosis safe: adding owners](https://help.gnosis-safe.io/en/articles/3950657-add-owners).
```suggestion
More admins can be added later, for more info, refer to [Gnosis safe: adding owners](https://help.gnosis-safe.io/en/articles/3950657-add-owners).
```

2023-02-02 03:45 UTC, weiyuan95 commented on packages/smartcontracts/src/hardhat.config.ts
> +    enabled: true,
unintended?

2023-02-02 03:45 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function amountAfterFees(uint256 _amount) internal view returns (uint256 netAmountInWei) {
is this an intentional change?

2023-02-02 03:45 UTC, weiyuan95 commented on README.md
> +### Bridge Ether - to transfer ETHER from an EOA to the Bridge
This section can be removed too after #276 🤣

2023-02-02 06:53 UTC, Abhishekkochar commented on README.md
> +## Fund Bridge with ETHER and ERC20 tokens
I removed this on PR #289

2023-02-02 06:56 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function amountAfterFees(uint256 _amount) internal view returns (uint256 netAmountInWei) {
Yes, In term of gas, both are the same. Only difference is visibility. When `private` only this contract can use this function. When `internal` inherited contracts can use that.

2023-02-05 07:38 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function amountAfterFees(uint256 _amount) internal view returns (uint256 netAmountInWei) {
Hmm, why would a contract need to inherit from BridgeV1? 🤔

2023-02-05 07:40 UTC, weiyuan95 approved these changes
This LGTM, just 1 quick question on the contract method visibility / inheritance

2023-02-06 04:25 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    function amountAfterFees(uint256 _amount) internal view returns (uint256 netAmountInWei) {
This function is only view, so no state change. Even if we put it to public, this won't change anything except the deployment cost.

2023-02-06 06:34 UTC, merged