feature(ui-ux): generate address api integration
WavesHQ/bridge pull request #286
Opened 2023-02-02 04:14 UTC by fullstackninja864

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #241

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-03 05:35 UTC, weiyuan95 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const lastIndex = await Prisma.pathIndex.findFirst({
What are the concurrency guarantees here? Could two servers act on the same index?

2023-02-03 06:05 UTC, weiyuan95 commented on apps/server/test-i9n/defichain/wallet.i9n.ts
> +        host: 5432,
Server  tests should not need to depend on a local `.env` file to run the tests. This makes the tests very brittle since we can only have 1 instance of a Postgres container running on `5432` at any given time.

I've already spoken to @greggtan on how we can handle this (since his PR is blocked by this), he will be working on the necessary changes to shift away from this design to a more dynamic one.

2023-02-03 07:10 UTC, fullstackninja864 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const lastIndex = await Prisma.pathIndex.findFirst({
two servers cant act on the same index with the above logic as we have unique index on `index` attribute which gives us pathIndex for address generation.
in case of concurrent request, only one of them will get fulfilled and will return the response and all remaining will get failed. on client side also we have added max retry as 3, so that in case of this concurrent failure, FE will reinitiate request and get the address

2023-02-06 05:17 UTC, pierregee requested changes

2023-02-06 05:17 UTC, pierregee commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +            if (data?.statusCode === 429) {
can use enum here

2023-02-06 05:17 UTC, pierregee commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +          .catch(({ data }) => {
Can we also handle the generic error (500) for unexpected errors?
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/13292662/216888537-4a47cc8d-81e1-4d45-aca8-ce3602c858c7.png">

2023-02-06 05:17 UTC, pierregee commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                    onClick={async () => handleGenerateNewDfcAddress()}
Duplicate code

2023-02-06 05:23 UTC, fullstackninja864 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const nextIndex = index ? index + 1 : 2;
If its undefined then next index will be 2, same for value 0 (as zero is false value). it the index value cant be zero until anyone add manual entry in db

2023-02-06 05:33 UTC, fullstackninja864 commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +          .catch(({ data }) => {
Will add this in new address creation flow PR

2023-02-06 05:47 UTC, pierregee commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const nextIndex = index ? index + 1 : 2;
Yaa just a minor nitpic, I was wondering if we could add that code explicitly as that logic above is not "immediately obvious"

2023-02-06 05:55 UTC, pierregee commented on apps/server/test-i9n/PostgreSql.i9n.ts
>    it('should throw error by passing duplicate index', async () => {
Let's add the same test case for address (duplicate)

2023-02-06 06:29 UTC, pierregee approved these changes
LGTM, thanks for the quick fixes! 
As discussed, 
1. Fix for the unallocated port: 5432 in e2e is not part of this PR
2. Fix for generic error generate-address endpoint will be handled on the next PR

2023-02-06 06:59 UTC, lykalabrada commented
Can definitely be included in the new upcoming PR, but can we fix this issue and handle passing of lowercase network from UI?
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/17063281/216904100-fae3c826-fa2c-4cd5-9b53-f7cbb0f86d9b.png">

2023-02-06 08:07 UTC, lykalabrada approved these changes
As discussed, some of the flow/UI changes will be covered on a separate PR 🙏

2023-02-07 05:44 UTC, lykalabrada approved these changes

2023-02-07 05:47 UTC, pierregee approved these changes

2023-02-08 05:13 UTC, thedoublejay requested changes

2023-02-08 05:13 UTC, thedoublejay commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const nextIndex = index ? index + 1 : 2;
Shouldn't we throw an error if index is undefined? We cannot always assume it's 2

2023-02-08 05:13 UTC, thedoublejay commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +          network,
Remove network usage

2023-02-08 05:13 UTC, thedoublejay commented on apps/server/src/prisma/migrations/20230203080350_init/migration.sql
> +    "network" "Network" NOT NULL,
same, let's remove network usage

2023-02-08 05:13 UTC, thedoublejay commented on pnpm-lock.yaml
> +      '@waveshq/standard-web-linter': ^0.39.0
need to revert

2023-02-08 05:13 UTC, thedoublejay commented on pnpm-lock.yaml
> +      '@reduxjs/toolkit': 1.9.2_react@18.2.0
I think no need to add this, already included on standard if i;m not mistaken

2023-02-08 05:17 UTC, thedoublejay requested changes

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/package.json
> +    "@waveshq/standard-web-linter":  "^0.39.0",
you added it here twice

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/package.json
> -    "playground:start": "docker-compose rm -fsv && docker-compose -f ../../docker-compose.yml up",
good idea that you put it on turbo. Can you remove the one on server as well, thanks!

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                error="Address has expired and is now unavailable for use."
Can we ask for a better copy for this?

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +function debounce(func, wait) {
Isn't this available on lodash?

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +        generateAddress({ network: networkEnv })
await here instead of then?

2023-02-08 05:17 UTC, thedoublejay commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                  <QRCode value={dfcUniqueAddress} size={160} />
check if this is scannable (QR)

2023-02-08 06:34 UTC, weiyuan95 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const lastIndex = await Prisma.pathIndex.findFirst({
Got it - i'm guessing a second `pathIndex.create` using the same index will fail since it will violate the `unique` constraint.

Do you think it's possible to test this behaviour to check that it fails as expected? Something like `Promise.all([generateAddress(), generateAddress()])`? 🤔

2023-02-08 08:29 UTC, fullstackninja864 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const nextIndex = index ? index + 1 : 2;
If its undefined i.e. there is no previous entry in DB, so in that case we have to start creating address from index 2

2023-02-08 08:46 UTC, fullstackninja864 commented on apps/web/package.json
> +    "@waveshq/standard-web-linter":  "^0.39.0",
Merge conflict i guess, will remove this

2023-02-08 10:13 UTC, fullstackninja864 commented on pnpm-lock.yaml
> +      '@reduxjs/toolkit': 1.9.2_react@18.2.0
its included in reduxjs, but we dont have reduxjs installed  as we are not using it

2023-02-08 10:16 UTC, fullstackninja864 commented on apps/web/package.json
> -    "playground:start": "docker-compose rm -fsv && docker-compose -f ../../docker-compose.yml up",
We will need one on server side to actually strat the playground

2023-02-08 10:16 UTC, fullstackninja864 commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                error="Address has expired and is now unavailable for use."
This will get removed in next PR

2023-02-08 10:17 UTC, fullstackninja864 commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +function debounce(func, wait) {
for single use I have avoided installing new lib

2023-02-09 03:47 UTC, fullstackninja864 commented on apps/web/src/components/erc-transfer/StepTwoSendConfirmation.tsx
> +                  <QRCode value={dfcUniqueAddress} size={160} />
QR is working, tested it with LW input also

2023-02-10 04:06 UTC, fullstackninja864 commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +      const lastIndex = await Prisma.pathIndex.findFirst({
Will address this in next PR

2023-02-11 02:01 UTC, thedoublejay requested changes

2023-02-11 02:01 UTC, thedoublejay commented on apps/web/src/layouts/contexts/NetworkEnvironmentContext.tsx
> +const NETWORK_ENV_DISPLAY_NAME: Record<EnvironmentNetwork, string> = {
@fullstackninja864 Isn't this the same with the values on Enum? You can fix it on your next PR

2023-02-11 02:01 UTC, thedoublejay commented on apps/web/src/store/website.tsx
> +  reducerPath: "website",
Why is it called website? Maybe DeFiChain wallet? or defichain?

2023-02-13 02:11 UTC, thedoublejay requested changes

2023-02-13 02:11 UTC, thedoublejay commented on apps/server/prisma/schema.prisma
>  model PathIndex {
Is it possible to rename this? To DeFiChainAddressIndex

2023-02-13 03:24 UTC, fullstackninja864 commented on apps/web/src/store/website.tsx
> +  reducerPath: "website",
Will update this in next pr

2023-02-13 03:25 UTC, fullstackninja864 commented on apps/server/prisma/schema.prisma
>  model PathIndex {
Will update this in next PR

2023-02-13 05:37 UTC, merged