feature(ui-ux): added bg image for main page
WavesHQ/bridge pull request #31
Opened 2022-11-28 12:17 UTC by fullstackninja864

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2022-11-29 09:21 UTC, thedoublejay requested changes

2022-11-29 09:21 UTC, thedoublejay commented on apps/web/src/pages/index.tsx
> +      className="relative min-h-screen flex flex-col mt-8 md:mt-7 lg:mt-12"
can we keep this? So if bg extends, at least it's still black. Also while bg image is loading

2022-11-29 17:42 UTC, fullstackninja864 commented on apps/web/src/pages/index.tsx
> +      className="relative min-h-screen flex flex-col mt-8 md:mt-7 lg:mt-12"
For that only we have added `bg-dark-00` to its parent component [here](https://github.com/WavesHQ/bridge/pull/31/files#diff-4c86ca9ac29c8ea2cea7997ea76d9d7ff6f7f529e594711a2f1795b588973993R35)

2022-11-30 04:36 UTC, thedoublejay approved these changes

2022-11-30 04:37 UTC, merged