Finish basic functionalities in contracts and basic tests
WavesHQ/bridge pull request #323
Opened 2023-02-07 10:29 UTC by cuongquangnam

#### What this PR does / why we need it:
Implement flushFund function

#### Which issue(s) does this PR fixes?:
#277 

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-08 08:08 UTC, cuongquangnam commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    expect(await testToken2.balanceOf(flushReceiveSigner.address)).to.equal(toWei('0'));
it is the balance of the signer, not the contract, the balance of contract is still 0, haha

2023-02-09 03:47 UTC, Abhishekkochar requested changes

2023-02-09 03:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +        for (uint256 i = 0; i < supportedTokens.length(); i++) {
```suggestion
        for (uint256 i = 0; i < supportedTokens.length(); ++i) {
```
Will do the same thing, however saves us 5 units. More [here](https://cygaar.substack.com/p/why-i-is-cheaper-than-i-in-solidity)

2023-02-09 03:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    const ERC20 = await ethers.getContractFactory('TestToken');
We can import `testToken` from loadFixture. We can avoid repetition.

2023-02-09 03:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    const ERC20 = await ethers.getContractFactory('TestToken');
Same as mentioned earlier

2023-02-09 03:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should be able to change flushReceiveAddress', async () => {
It will be good, if we can get similar to [this](https://github.com/WavesHQ/bridge/blob/main/packages/smartcontracts/src/tests/BridgeProxy.Withdraw.spec.ts#L8). Sanity check only admins can call this function.

2023-02-09 03:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    await proxyBridge.changeFlushReceiveAddress(newFlushReceiveAddress);
```suggestion
    await proxyBridge.connect(defaultAdmin).changeFlushReceiveAddress(newFlushReceiveAddress);
```

2023-02-09 09:59 UTC, weiyuan95 requested changes
IMO the logic is sound, we can work on bolstering the test cases later.

2023-02-09 09:59 UTC, weiyuan95 commented on apps/server/package.json
> +    "next": "^13.1.6",
Not intended?🤔

2023-02-09 09:59 UTC, weiyuan95 commented on apps/web/package.json
> +    "next": "^13.1.6",
Same here

2023-02-09 09:59 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +                // in the period for addingSupport or changingDailyAllowane, we will not flush for the token
```suggestion
                // the same logic as in bridgeToDeFiChain applies here, if we are still
                // in the period for addingSupport or changingDailyAllowance, we will not flush for that particular token
```

2023-02-09 09:59 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * @notice to get the supported tokens, as recursive data structure (supportedTokens) cannot be made public
```suggestion
     * @notice to get the ERC20 addresses of supported tokens, as recursive data structure (supportedTokens) cannot be made public
```
Some questions:
- What does it mean by recursive data structure? Isn't this just the values of the set?
- Why cant `supportTokens` be public? 🤔 Some limitation of the utility?

2023-02-09 09:59 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    expect(latestResetTimestampAfterAddingSupport).to.equal((await time.latest()) + 59);
```suggestion
    const expectedTime = getCurrentTimeStamp({ additionalTime: 60 });
    // latestResetTimestamp = block.timestamp + 59 = X + 59
    await proxyBridge.addSupportedTokens(testToken.address, toWei('10'), expectedTime);
    const latestResetTimestampAfterAddingSupport = (await proxyBridge.tokenAllowances(testToken.address))
      .latestResetTimestamp;
    expect(latestResetTimestampAfterAddingSupport).to.equal(expectedTime);
```

I'm guessing you were previously calling `getCurrentTimeStamp` multiple times, which was causing some time errors. If we did it in this manner with a constant reference point for the time, I don't think we'll have the problem of wrong timestamps (hardhat's `time.now()` vs node's `Date.now()`)

We can adjust the tests at the later date though - the logic still looks sound to me.

2023-02-09 09:59 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    const balanceBridgeBefore2ndFlush = await testToken.balanceOf(proxyBridge.address);
```suggestion
    const bridgeBalanceBefore2ndFlush = await testToken.balanceOf(proxyBridge.address);
```

Same for the other variables as well.

2023-02-09 09:59 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should not flush fund for a token if it is in the change allowance period', async () => {
Since this test is a lot more complex, it'll be good to have some comments for it. For example
```ts
// mint 100 tokens to bridge
...
...
// Change dailyAllowance of bridge
// Call flush funds
// Funds should not be flushed since it is not officially supported yet
// Advance time till token is supported
// Flush funds
// Bridge should have correct balance after correct amount is flushed (20 * 2)
```
Would help to break up the code and expectations into blocks that are easier to read and helps the user to understand the test too.

It'll also be good to have some math to help readers keep track, for eg
```ts
// 40 (current amount on bridge) + 100 (newly minted) - 20 (flushed amount)
```

2023-02-09 15:23 UTC, cuongquangnam commented on apps/web/package.json
> +    "next": "^13.1.6",
Oh, I was trying to add this when the hooks before my commit broke. It said next is not found ...

2023-02-09 15:51 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +     * @notice to get the supported tokens, as recursive data structure (supportedTokens) cannot be made public
The compiler will fail when you make supportedTokens public: 
 `TypeError: Internal or recursive type is not allowed for public state variables.`
My guess at that point is that supportedTokens, which is of type AddressSet ( https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableSet.sol#L233) and this type is recursive ( a struct inside a struct)

2023-02-10 06:09 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +    expect(latestResetTimestampAfterAddingSupport).to.equal((await time.latest()) + 59);
Problem has been figured out. Opened https://github.com/WavesHQ/bridge/issues/357 to make sure that we use the fix approach as well for the other tests instead of the current `getCurrentTimeStamp` as well.

2023-02-10 06:10 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.flushFund.spec.ts
> +  it('Should not flush fund for a token if it is in the change allowance period', async () => {
With the current approach, remember to make a note on how much the timestamp advances as well 😛

2023-02-10 07:32 UTC, cuongquangnam commented on apps/server/package.json
> +    "next": "^13.1.6",
Reverted changes on this

2023-02-10 07:32 UTC, cuongquangnam commented on apps/web/package.json
> +    "next": "^13.1.6",
Reverted changes on this

2023-02-10 07:57 UTC, weiyuan95 approved these changes
Approving and merging this in. The Hardhat test is a bit messy right now, but it will be tackled in #357 . It should not have any impact on the actual contract logic.

2023-02-10 07:58 UTC, merged