feat(server): sign claims data
WavesHQ/bridge pull request #324
Opened 2023-02-07 11:24 UTC by lykalabrada

#### What this PR does / why we need it:
Added API to signs claims and return signature and nonce. This API will called before user can `claimFund`.
Another PR for frontend to integrate this API will be raised later.

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [x] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-08 06:37 UTC, weiyuan95 commented on apps/server/src/AppService.ts
> +interface SignClaim {
Minor nit here but I would rather put this on the bottom of the file 😛

2023-02-08 06:56 UTC, weiyuan95 requested changes
Left some comments on changes related to the server 😄

2023-02-08 06:56 UTC, weiyuan95 commented on apps/server/src/AppService.ts
> +    @Inject(ETHERS_RPC_PROVIDER) readonly ethersRpcProvider: ethers.providers.JsonRpcProvider,
Hmm, I would understand if this is necessary on the front end (since the network/url selected by the user is not static on metamask) but why is it non static on the server? Wouldn't the RPC url (and hence network) always be the same?

2023-02-08 06:56 UTC, weiyuan95 commented on apps/server/src/AppService.ts
> +      const signer = wallet.connect(this.ethersRpcProvider);
```suggestion
      const wallet = new ethers.Wallet(this.configService.getOrThrow('ethereum.testnet.ethWalletPrivKey'), this.ethersRpcProvider);
```

We can skip the redundant `connect` call by passing it in directly to the constructor.

2023-02-08 06:56 UTC, weiyuan95 commented on apps/server/src/AppService.ts
> +        deadline: ethers.constants.MaxUint256,
The deadline should be 2359 GMT of the current day, but i'm guessing that will be an implementation that might come later 😛

2023-02-08 06:56 UTC, weiyuan95 commented on apps/web/src/config/ABIs/testnet/BridgeV1.json
> +  { "inputs": [], "name": "DO_NOT_SEND_ETHER_WITH_ERC20", "type": "error" },
Instead of hardcoding this,`app/web` can have a dependency on `"smartcontracts": "workspace:0.0.0",` so that we can access the ABI with `BridgeV1__factory.abi`. I will also always be the correct version, no need to manually update!

2023-02-08 14:03 UTC, merged

2023-02-09 01:16 UTC, pierregee commented
Sorry @lykalabrada! I think it was automerged when I was debugging it on `verify-funds` branch and pushed it! Thanks for reopening and pointing to main

2023-02-09 01:27 UTC, lykalabrada commented on apps/server/src/AppService.ts
> +    @Inject(ETHERS_RPC_PROVIDER) readonly ethersRpcProvider: ethers.providers.JsonRpcProvider,
Sry I was just testing around and forgot to revert this, thanks for checking!

2023-02-09 02:34 UTC, lykalabrada commented on apps/web/src/config/ABIs/testnet/BridgeV1.json
> +  { "inputs": [], "name": "DO_NOT_SEND_ETHER_WITH_ERC20", "type": "error" },
Good point! Since this is on the web side we will update this on a completely separate PR.
For the other comments above, fixed on [this PR](https://github.com/WavesHQ/bridge/pull/344) 🙏