feat(core): verify funds - EVM -> DFC
WavesHQ/bridge pull request #330
Opened 2023-02-08 05:09 UTC by pierregee

#### What this PR does / why we need it:
- [ ] Create /verify endpoint to verify if the balance is in the wallet's address
- [ ] Handle edge cases - display custom error code in UI to help debugging 
- [ ] Call signClaims inside verify
- [ ] Add e2e tests

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-14 04:48 UTC, weiyuan95 requested changes

2023-02-14 04:48 UTC, weiyuan95 commented on apps/server/src/defichain/model/VerifyDto.ts
> +  @IsString()
Can probably use `IsNumberString`, more decorators [here](https://github.com/typestack/class-validator#validation-decorators). Then we can also check for things like is the number positive, etc.

2023-02-14 04:48 UTC, weiyuan95 commented on apps/server/src/defichain/model/VerifyDto.ts
> +}
Since this class only exists for data validation and transfer, we can have a data class which represents the object we want to deal with in our server. For eg.
```ts
class VerifyObject {
  constructor(public readonly amount: BigNumber, ...) { }
}
```
and then we have 

```ts
class VerifyDto {
  // ...
  // same as current implementation
  // ...

  toObj(): VerifyObject {
    return new VerifyObject(new BigNumber(this.amount), ...)
  }
}
```

And then we work with `VerifyObject` in our code instead of `VerifyDto`

2023-02-14 04:48 UTC, weiyuan95 commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
We can actually write more succinct validation tests with `it.each` (basically a for loop for jest's `it`). For example in this case:

```ts
// needs some setup
type MockedPayload = {
  amount: string,
  symbol: string,
  address: string
}
function mockPayload(params: Partial<MockedPayload>): MockedPayload {
  return {
    amount: '1',
    symbol: 'BTC',
    address: 'abc1234',
    ...params // overrides any of the 'right' values
  }
}

it.each([
  mockPayload({address: '10923'})
  // ...
])(`Should fail request with invalid request %p`, async(mockedPayload) => {
    // use mock payload
    // in this loop mockedPayload == {amount: '1', symbol: 'btc', address: '10923'}
})

```

2023-02-14 06:44 UTC, pierregee commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
Grouping it in `.each` is tempting! But looping it in such way won't be able to run some code prerequisites unique to each test like [1](https://github.com/WavesHQ/bridge/pull/330/files#diff-48b02ff748a2982153d8aefeeaddb3befc212ca03ba354f843b8bbb864b6f23fR112-R125) [2](https://github.com/WavesHQ/bridge/pull/330/files#diff-48b02ff748a2982153d8aefeeaddb3befc212ca03ba354f843b8bbb864b6f23fR131-R150) 🤔

2023-02-14 06:44 UTC, pierregee commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
Tried it still and it seems the first param of `it.each()` isn't waiting for "beforeAll" so some vars can't be retrieved

2023-02-14 06:47 UTC, pierregee commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
To make it "at least" more succinct, how about putting the api call in a function? Helps a bit..
``` 
async function verify(mockedPayload: MockedPayload) {
    const initialResponse = await testing.inject({
      method: 'POST',
      url: `${VERIFY_ENDPOINT}`,
      payload: mockedPayload,
    });
    const response = JSON.parse(initialResponse.body);

    return response;
  }


it('should throw error if symbol is not valid', async () => {
  const initialResponse = await verify({
    amount: '1',
    symbol: '_invalid_symbol_',
    address: localAddress,
  });
  expect(initialResponse).toStrictEqual({ isValid: false, statusCode: CustomErrorCodes.TokenSymbolNotValid });
});
```

2023-02-14 07:14 UTC, weiyuan95 commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
> Tried it still and it seems the first param of it.each() isn't waiting for "beforeAll" so some vars can't be retrieved

Ah ok, we need the `localAddress` to actually confirm that the verify flow works, and it cannot be any generic valid address since i'm guessing that won't be in the DB.

Yep, I think what you've suggested works as well, since we don't really care about the `inject` and `response` code, what's important is the `params` used to call the endpoint 😬

2023-02-14 08:07 UTC, thedoublejay requested changes

2023-02-14 08:07 UTC, thedoublejay commented on apps/server/src/defichain/controllers/WhaleWalletController.ts
> -  @Throttle(5, 60)
Why we removed this?

2023-02-14 08:07 UTC, thedoublejay commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +    network: EnvironmentNetwork = EnvironmentNetwork.MainNet,
This shouldn't be optional

2023-02-14 08:07 UTC, thedoublejay commented on apps/server/src/defichain/services/WhaleWalletService.ts
> +    network: EnvironmentNetwork = EnvironmentNetwork.MainNet,
Since we're already requiring it on the client, I think just remove the default values

2023-02-14 08:12 UTC, weiyuan95 commented on apps/server/src/defichain/controllers/WhaleWalletController.ts
> -  @Throttle(5, 60)
Starting to think that the throttle should just be set globally instead of on a controller level 🤔

2023-02-14 11:04 UTC, thedoublejay commented on apps/server/src/defichain/controllers/WhaleWalletController.ts
> -  @Throttle(5, 60)
But some endpoints should have stricter throttles, like this which stores new data on the DB

2023-02-14 11:04 UTC, thedoublejay commented on apps/server/src/defichain/controllers/WhaleWalletController.ts
> -  @Throttle(5, 60)
While others can be more lenient

2023-02-15 03:04 UTC, pierregee commented on apps/server/src/defichain/model/VerifyDto.ts
> +}
I'm not quite sure how this would work in the controller level 🤔 
```
  @Post('verify')
  async verify(@Body() body: VerifyDto): Promise<{ isValid: boolean; statusCode?: CustomErrorCodes }> {

    // doesn't work
    return this.whaleWalletService.verify(
      body.toObj(), // won't work because toObj is undefined
      this.network,
    );
  
    // this works
    return this.whaleWalletService.verify(
      new VerifyObject(new BigNumber(body.amount), body.address, body.symbol),
      this.network,
    );
  }
```

2023-02-15 03:39 UTC, weiyuan95 commented on apps/server/src/defichain/model/VerifyDto.ts
> +}
Ah sorry, mixing up implementations across different repos. We'll need to `transform` the object since it's just a plan JS object over the wire.

https://docs.nestjs.com/techniques/validation#transform-payload-objects

2023-02-15 06:38 UTC, pierregee commented on apps/server/src/defichain/controllers/WhaleWalletController.ts
> -  @Throttle(5, 60)
Ah ok sure, moved it back here to endpoint-level! I have to use a [config](https://github.com/WavesHQ/bridge/pull/330/files#diff-9bb3e234e20f4e46dad3d85462312a05f11e9c3b201e4233009c2a92b98bc153R33) to be able to test it. I haven't deep dive yet if there's a NestJS way of configuring the limit in e2e tests so I used config + jest.mock

2023-02-15 06:39 UTC, pierregee commented on apps/server/test-i9n/defichain/verify.i9n.ts
> +  it('should throw error if symbol is not valid', async () => {
Yes, implemented the verify function above instead! Lemmeknow if it can be improved 🙏

2023-02-15 06:40 UTC, pierregee commented on apps/server/src/defichain/model/VerifyDto.ts
> +}
This works! Thanks for sharing

2023-02-16 00:59 UTC, merged