feature(ui-ux): maintenance screen
WavesHQ/bridge pull request #360
Opened 2023-02-10 16:52 UTC by chloezxyy

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-13 02:48 UTC, pierregee requested changes

2023-02-13 02:48 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +            <div className="font-semibold">Version 1.0.1&nbsp;</div>
Let's remove the versioning

2023-02-13 02:48 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +                {SocialItemsFooter.map(({ href, testId, icon: Icon }) => (
The links redirect to defich instead of BR social accounts (github and twitter)

2023-02-13 02:48 UTC, pierregee commented on apps/web/src/pages/Maintenance.tsx
> +                        Twitter (Birthday Research)
Forgot to redirect it to the social links?

2023-02-13 02:48 UTC, pierregee commented on apps/web/src/pages/Maintenance.tsx
> +                        Github (Birthday Research)
same here

2023-02-15 07:07 UTC, pierregee requested changes

2023-02-15 09:35 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +            </div>
It's feasible to just have one code for all viewports for this whole block. Let's prevent duplicates if possible 😁

2023-02-15 13:56 UTC, pierregee requested changes

2023-02-15 13:56 UTC, pierregee commented on apps/web/cypress/e2e/index.spec.ts
> +    BirthdayResearchSocialItems.forEach((BirthdayResearchSocialItem) => {
use the native `it.each` instead

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +    <footer
<img width="892" alt="image" src="https://user-images.githubusercontent.com/13292662/219039750-ba9b24f7-7333-4faf-bb36-e7c98450d0c9.png">
Missing black background on the footer

design:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/13292662/219039982-38751d59-3e15-4247-8336-319427be2064.png">

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +          <div className="relative h-[28px] w-[250px] cursor-pointer mt-3">
is this supposed to be clickable? if no, let's remove the cursor-pointer

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +        <div className="border-t-[0.5px] dark:border-dark-300 xs:pb-[17.5px] pt-[15px]">
```suggestion
        <div className="border-t-[0.5px] border-dark-300 xs:pb-[17.5px] pt-[15px]">
```

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/components/Footer.tsx
> +      className="bg-inherit relative z-[1] w-full border-dark-300 pt-4 md:pt-3"
what does bg-inherit do? Removing it looks the same to me 🤔

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/pages/Maintenance.tsx
> +        <Container className="mx-0 min-h-screen" data-testid="homepage">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/13292662/219043492-30840b64-550e-47b1-82f9-c05c106fac9c.png">
Not aligned as per the design

2023-02-15 13:56 UTC, pierregee commented on apps/web/src/pages/Maintenance.tsx
> +                        <span className="ml-2 text-base font-semibold ">
```suggestion
                        <span className="ml-4 text-base">
```

2023-02-16 06:10 UTC, chloezxyy commented on apps/web/src/pages/ScreenContainer.tsx
> +        </div>
The main screen's background design and the Maintenance's screen's are different, same with the Footer

2023-02-16 07:17 UTC, chloezxyy commented on apps/web/cypress/e2e/index.spec.ts
> +    BirthdayResearchSocialItems.forEach((BirthdayResearchSocialItem) => {
As discussed, will circle back

2023-02-16 08:22 UTC, chloezxyy commented on apps/web/src/pages/ScreenContainer.tsx
> +        </div>
Refactored

2023-02-16 12:26 UTC, pierregee reviewed
LGTM, just need to add the API to check if it's up or not

2023-02-16 12:28 UTC, pierregee approved these changes
Approving this. The API integration to maintenance status can be created in another PR

2023-02-16 12:28 UTC, merged