feature(ui-ux): display browser reload modal
WavesHQ/bridge pull request #400
Opened 2023-02-15 10:24 UTC by JoshuaC817

#### What this PR does / why we need it:
Display a native reload warning modal when there is an unconfirmed transaction ongoing

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:
Reference for [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) method used
Reasons for not being able to customize a modal or message is that:
1. User should have full control and be able to close any browser
2. Having a customized message will possibly let scammers to mislead users

How it looks like on:
Chrome (Mac)
<img width="272" alt="image" src="https://user-images.githubusercontent.com/89639796/218999975-5cccafa0-6bc0-4f51-93e2-4e205876519b.png">

Safari
<img width="264" alt="image" src="https://user-images.githubusercontent.com/89639796/219000131-90de8184-5cca-4278-9354-89285696784b.png">

Firefox (Mac)
<img width="381" alt="image" src="https://user-images.githubusercontent.com/89639796/219000220-06532ed3-2d40-47bc-8a39-3efd28c4196c.png">

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-21 07:46 UTC, JoshuaC817 commented on apps/web/src/pages/index.tsx
> +      const localData = getStorageItem<UnconfirmedTxnI>(TXN_KEY);
> We might have to change this once we start storing the `txn hash` in the local storage. It's a better indicator because if there's a txn hash -> there's really an unconfirmed txn. This `TXN_KEY` is also being used to save the form state

Done, updated to use `txn hash`



> Another one we might have to consider is if we'll have to reset the form if the user chooses to reload (Form has values,but no unconfirmed txn yet)

Don't think we need to reset the form if the form has value but no unconfirmed txn, this would defeat the purpose of storing it and repopulating the value back in form

2023-02-21 07:49 UTC, JoshuaC817 commented
EVM > DFC
Will only show reload warning modal when there is `UNCONFIRMED_TXN_HASH_KEY` (which is while waiting for 65 blocks of confirmation)

DFC > EVM
Not showing any reload warning modal since we don't have any long waiting API

2023-02-22 02:57 UTC, pierregee commented on apps/web/src/pages/index.tsx
> +      if (unconfirmedHash !== undefined) {
```suggestion
      const unconfirmedHash = getStorageItem<string>(UNCONFIRMED_TXN_HASH_KEY);
      const unsentFundHash = getStorageItem<string>(UNSENT_FUND_TXN_HASH_KEY);
      if (unconfirmedHash !== undefined || unsentFundHash !== undefined) {
```
Let's also add a warning for this state

2023-02-22 02:58 UTC, pierregee requested changes

2023-02-22 02:58 UTC, pierregee commented on apps/web/src/pages/index.tsx
> +      if (unconfirmedHash !== undefined) {
```suggestion
      const unconfirmedHash = getStorageItem<string>(UNCONFIRMED_TXN_HASH_KEY);
      const unsentFundHash = getStorageItem<string>(UNSENT_FUND_TXN_HASH_KEY);
      if (unconfirmedHash !== undefined || unsentFundHash !== undefined) {
```
Let's also add a warning for this state

2023-02-22 02:58 UTC, pierregee commented on apps/web/src/pages/index.tsx
> +  }, [UNCONFIRMED_TXN_HASH_KEY]);
```suggestion
  }, [UNCONFIRMED_TXN_HASH_KEY, UNSENT_FUND_TXN_HASH_KEY]);
```

2023-02-22 03:07 UTC, JoshuaC817 commented on apps/web/src/pages/index.tsx
> +      if (unconfirmedHash !== undefined) {
Alright done!

2023-02-22 03:07 UTC, JoshuaC817 commented on apps/web/src/pages/index.tsx
> +  }, [UNCONFIRMED_TXN_HASH_KEY]);
Done done

2023-02-22 04:10 UTC, pierregee approved these changes

2023-02-22 04:10 UTC, merged