feature(server): implemented allocateDFCFund endpoint (WIP)
WavesHQ/bridge pull request #433
Opened 2023-02-17 05:16 UTC by fullstackninja864

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-19 04:42 UTC, thedoublejay requested changes

2023-02-19 04:42 UTC, thedoublejay commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      const txHash = await this.sendService.send(address, {
Can we store defichain txHash as well? For auditing purposes

2023-02-20 03:38 UTC, pierregee requested changes

2023-02-20 03:38 UTC, pierregee commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      const txHash = await this.sendService.send(address, {
Need to handle if the hot wallet doesn't have enough balance

2023-02-20 03:38 UTC, pierregee commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +      const txHash = await this.sendService.send(address, {
Also need an explicit response/error that the funds didn't go through so it can be properly handled in ui
<img width="471" alt="image" src="https://user-images.githubusercontent.com/13292662/220003529-5da27752-7429-4b17-a1ed-6828e8acad32.png">

2023-02-21 03:45 UTC, merged