Fix bug in claimFund and add several security improvements
WavesHQ/bridge pull request #467
Opened 2023-02-21 09:25 UTC by cuongquangnam

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] No console errors on web
- [ ] Tested on Light mode and Dark mode\*
- [ ] Your UI implementation visually matched the rendered design\*
- [ ] Unit tests\*
- [ ] Added e2e tests\*
- [ ] Added translations\*

2023-02-22 10:36 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
>  pragma solidity ^0.8.13;
These changes should be made on the `BridgeV2` contract first right? @Abhishekkochar

2023-02-22 10:49 UTC, weiyuan95 commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    EnumerableSetUpgradeable.AddressSet internal supportedTokens;
I'm assuming we're using this because of https://docs.openzeppelin.com/contracts/4.x/upgradeable

Can we double check if we've missed out any other contracts that should be `*Upgradable`?

2023-02-23 00:47 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
>  pragma solidity ^0.8.13;
Ideally yes, we can make this part of V3.

2023-02-23 02:58 UTC, Abhishekkochar requested changes
Minor changes. Other than this LGTM.

2023-02-23 02:58 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
> +      await proxyBridge.claimFund(
```suggestion
      await proxyBridge.connect(defaultAdminSigner).claimFund(
```

2023-02-23 02:58 UTC, Abhishekkochar commented on packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
> +          operationalAdminSigner.address,
We are already testing this case above. Can we change this to `arbitrarySigner`? Will still revert with custom error, however more diversify.

2023-02-23 03:02 UTC, cuongquangnam commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    EnumerableSetUpgradeable.AddressSet internal supportedTokens;
Yeah, I think it is a good practice that all contracts imported for the implementation contract are upgradeable (though we don't need to use upgradeable version for the smart contracts that don't have state variables IMO) Also, this helps avoid duplicate of deployed smart contracts (e.g. in the previous [deployment](https://goerli.etherscan.io/address/0x0d269d012fffd93b448c0090740241c8e9556031#code) there are Strings and StringsUpgrdeable contracts)

2023-02-23 03:26 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/BridgeV1.sol
> +    EnumerableSetUpgradeable.AddressSet internal supportedTokens;
We will be using `StringsUpgrdeable` if we have to reinit the contract. [https://github.com/WavesHQ/bridge/blob/54dc0b7fb34b66637486c18a929a1695cc2b9f20/pa[…]rtcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol](https://github.com/WavesHQ/bridge/blob/54dc0b7fb34b66637486c18a929a1695cc2b9f20/packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol#L408) unless backend does the conversion from big number to string.

2023-02-23 06:59 UTC, Abhishekkochar commented on packages/smartcontracts/src/contracts/test/reinitialize/BridgeV2TestNet.sol
> +    using EnumerableSetUpgradeable for EnumerableSetUpgradeable.AddressSet;
Oh forgot about these one  😅😅

2023-02-23 08:24 UTC, weiyuan95 commented on packages/smartcontracts/src/tests/BridgeProxy.defiToEvm.spec.ts
> +          operationalAdminSigner.address,
We are also testing for ETH here (ie. `0x00`) so I would say it's okay.

2023-02-23 21:49 UTC, Abhishekkochar commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +import { BridgeV1, BridgeV1__factory, ERC20__factory } from 'smartcontracts';
I'm certain we need `BridgeV2TestNet__factory` in the backend for testnet. Abi is different from BridgeV1__factory. @lykalabrada am I right?

2023-02-24 00:32 UTC, lykalabrada commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +import { BridgeV1, BridgeV1__factory, ERC20__factory } from 'smartcontracts';
Previously we had to use `BridgeV2TestNet__factory` because of [this issue](https://github.com/WavesHQ/bridge/issues/461) with `BridgeV1__factory`.

But I just tried switching back to `BridgeV1__factory` and `claimFund` is now working as well.
By right, should they be the same? I think BridgeV1__factory is more similar to our [ABI on testnet](https://goerli.etherscan.io/address/0x8b929b940bc0d4d26072e0d8d659b08961d6ff09#code)

2023-02-24 00:42 UTC, Abhishekkochar approved these changes

2023-02-24 00:50 UTC, weiyuan95 commented on apps/server/src/ethereum/services/EVMTransactionConfirmerService.ts
> +import { BridgeV1, BridgeV1__factory, ERC20__factory } from 'smartcontracts';
Bridgev1 and bridgev2tesnet contracts are at parity logic wise, we just need to use bridgev1 for the `initializer` modifer

2023-02-24 00:50 UTC, merged